import type {
  User,
  Cohort,
  Project,
  Deliverable,
  Task,
  Submission,
  Review,
  PortfolioProject,
  Activity,
  Notification,
  CareerResource,
  JobPosting,
} from './types'
import { allWorkstreams } from './workstream-data'

// Users (Students, Mentors, Admin)
export const mockUsers: User[] = [
  {
    id: 'admin-1',
    name: 'Sarah Admin',
    email: 'sarah@pixlpluzportal.demo',
    role: 'admin',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Sarah',
    createdAt: '2024-01-01T00:00:00Z',
  },
  {
    id: 'mentor-1',
    name: 'Alex Rivera',
    email: 'alex@pixlpluzportal.demo',
    role: 'mentor',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Alex',
    bio: 'Senior Frontend Engineer with 8 years of experience',
    skills: ['React', 'TypeScript', 'Next.js', 'UI/UX'],
    createdAt: '2024-01-15T00:00:00Z',
  },
  {
    id: 'mentor-2',
    name: 'Jordan Chen',
    email: 'jordan@pixlpluzportal.demo',
    role: 'mentor',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Jordan',
    bio: 'Full-stack Developer & Tech Lead',
    skills: ['Node.js', 'PostgreSQL', 'AWS', 'System Design'],
    createdAt: '2024-01-15T00:00:00Z',
  },
  {
    id: 'mentor-3',
    name: 'Morgan Lee',
    email: 'morgan@pixlpluzportal.demo',
    role: 'mentor',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Morgan',
    bio: 'Creative Technologist & Design Engineer',
    skills: ['Three.js', 'WebGL', 'Creative Coding', 'Animation'],
    createdAt: '2024-01-15T00:00:00Z',
  },
  {
    id: 'mentor-4',
    name: 'Taylor Kim',
    email: 'taylor@pixlpluzportal.demo',
    role: 'mentor',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Taylor',
    bio: 'DevOps Engineer & Cloud Architect',
    skills: ['Docker', 'Kubernetes', 'CI/CD', 'Terraform'],
    createdAt: '2024-01-15T00:00:00Z',
  },
  {
    id: 'mentor-5',
    name: 'Casey Park',
    email: 'casey@pixlpluzportal.demo',
    role: 'mentor',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Casey',
    bio: 'Product Designer turned Frontend Developer',
    skills: ['Figma', 'Design Systems', 'Accessibility', 'React'],
    createdAt: '2024-01-15T00:00:00Z',
  },
  {
    id: 'mentor-6',
    name: 'Jamie Patel',
    email: 'jamie@pixlpluzportal.demo',
    role: 'mentor',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Jamie',
    bio: 'AI/ML Engineer & Data Scientist',
    skills: ['Python', 'TensorFlow', 'LLMs', 'Data Visualization'],
    createdAt: '2024-01-15T00:00:00Z',
  },
  // Students – Cohort 1
  { id: 'student-1', name: 'Emma Thompson', email: 'emma@student.pixlpluzportal.demo', role: 'student', cohortId: 'cohort-1', avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Emma', skills: ['JavaScript', 'React', 'CSS'], githubUrl: 'https://github.com/emmathompson', createdAt: '2024-02-01T00:00:00Z' },
  { id: 'student-2', name: 'Liam Martinez', email: 'liam@student.pixlpluzportal.demo', role: 'student', cohortId: 'cohort-1', avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Liam', skills: ['Python', 'Django', 'SQL'], githubUrl: 'https://github.com/liammartinez', createdAt: '2024-02-01T00:00:00Z' },
  { id: 'student-3', name: 'Olivia Zhang', email: 'olivia@student.pixlpluzportal.demo', role: 'student', cohortId: 'cohort-1', avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Olivia', skills: ['Design', 'Figma', 'HTML/CSS'], githubUrl: 'https://github.com/oliviazhang', createdAt: '2024-02-01T00:00:00Z' },
  { id: 'student-4', name: 'Noah Johnson', email: 'noah@student.pixlpluzportal.demo', role: 'student', cohortId: 'cohort-1', avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Noah', skills: ['JavaScript', 'Node.js', 'MongoDB'], githubUrl: 'https://github.com/noahjohnson', createdAt: '2024-02-01T00:00:00Z' },
  { id: 'student-5', name: 'Ava Williams', email: 'ava@student.pixlpluzportal.demo', role: 'student', cohortId: 'cohort-1', avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Ava', skills: ['TypeScript', 'Vue.js', 'Tailwind'], githubUrl: 'https://github.com/avawilliams', createdAt: '2024-02-01T00:00:00Z' },
  { id: 'student-6', name: 'Ethan Brown', email: 'ethan@student.pixlpluzportal.demo', role: 'student', cohortId: 'cohort-1', avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Ethan', skills: ['React Native', 'Firebase', 'UI Design'], githubUrl: 'https://github.com/ethanbrown', createdAt: '2024-02-01T00:00:00Z' },
  { id: 'student-7', name: 'Sophia Davis', email: 'sophia@student.pixlpluzportal.demo', role: 'student', cohortId: 'cohort-1', avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Sophia', skills: ['Angular', 'Java', 'Spring Boot'], githubUrl: 'https://github.com/sophiadavis', createdAt: '2024-02-01T00:00:00Z' },
  { id: 'student-8', name: 'Mason Wilson', email: 'mason@student.pixlpluzportal.demo', role: 'student', cohortId: 'cohort-1', avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Mason', skills: ['PHP', 'Laravel', 'MySQL'], githubUrl: 'https://github.com/masonwilson', createdAt: '2024-02-01T00:00:00Z' },
  // Students – Cohort 2
  { id: 'student-9', name: 'Isabella Garcia', email: 'isabella@student.pixlpluzportal.demo', role: 'student', cohortId: 'cohort-2', avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Isabella', skills: ['React', 'Next.js', 'Vercel'], githubUrl: 'https://github.com/isabellagarcia', createdAt: '2024-03-01T00:00:00Z' },
  { id: 'student-10', name: 'Lucas Anderson', email: 'lucas@student.pixlpluzportal.demo', role: 'student', cohortId: 'cohort-2', avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Lucas', skills: ['Go', 'Docker', 'Microservices'], githubUrl: 'https://github.com/lucasanderson', createdAt: '2024-03-01T00:00:00Z' },
  { id: 'student-11', name: 'Mia Taylor', email: 'mia@student.pixlpluzportal.demo', role: 'student', cohortId: 'cohort-2', avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Mia', skills: ['Swift', 'iOS', 'SwiftUI'], githubUrl: 'https://github.com/miataylor', createdAt: '2024-03-01T00:00:00Z' },
  { id: 'student-12', name: 'Alexander Lee', email: 'alexander@student.pixlpluzportal.demo', role: 'student', cohortId: 'cohort-2', avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Alexander', skills: ['Kotlin', 'Android', 'Jetpack Compose'], githubUrl: 'https://github.com/alexanderlee', createdAt: '2024-03-01T00:00:00Z' },
  { id: 'student-13', name: 'Charlotte White', email: 'charlotte@student.pixlpluzportal.demo', role: 'student', cohortId: 'cohort-2', avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Charlotte', skills: ['Rust', 'WebAssembly', 'Systems Programming'], githubUrl: 'https://github.com/charlottewhite', createdAt: '2024-03-01T00:00:00Z' },
  { id: 'student-14', name: 'Benjamin Harris', email: 'benjamin@student.pixlpluzportal.demo', role: 'student', cohortId: 'cohort-2', avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Benjamin', skills: ['GraphQL', 'Apollo', 'PostgreSQL'], githubUrl: 'https://github.com/benjaminharris', createdAt: '2024-03-01T00:00:00Z' },
  { id: 'student-15', name: 'Amelia Martin', email: 'amelia@student.pixlpluzportal.demo', role: 'student', cohortId: 'cohort-2', avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Amelia', skills: ['Svelte', 'SvelteKit', 'CSS Animations'], githubUrl: 'https://github.com/ameliamartin', createdAt: '2024-03-01T00:00:00Z' },
  { id: 'student-16', name: 'James Thompson', email: 'james@student.pixlpluzportal.demo', role: 'student', cohortId: 'cohort-2', avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=James', skills: ['C#', '.NET', 'Azure'], githubUrl: 'https://github.com/jamesthompson', createdAt: '2024-03-01T00:00:00Z' },
  // Students – Cohort 3
  { id: 'student-17', name: 'Harper Martinez', email: 'harper@student.pixlpluzportal.demo', role: 'student', cohortId: 'cohort-3', avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Harper', skills: ['Python', 'FastAPI', 'AI/ML'], githubUrl: 'https://github.com/harpermartinez', createdAt: '2024-04-01T00:00:00Z' },
  { id: 'student-18', name: 'Elijah Garcia', email: 'elijah@student.pixlpluzportal.demo', role: 'student', cohortId: 'cohort-3', avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Elijah', skills: ['Vue 3', 'Nuxt', 'Pinia'], githubUrl: 'https://github.com/elijahgarcia', createdAt: '2024-04-01T00:00:00Z' },
  { id: 'student-19', name: 'Evelyn Rodriguez', email: 'evelyn@student.pixlpluzportal.demo', role: 'student', cohortId: 'cohort-3', avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Evelyn', skills: ['Flutter', 'Dart', 'Firebase'], githubUrl: 'https://github.com/evelynrodriguez', createdAt: '2024-04-01T00:00:00Z' },
  { id: 'student-20', name: 'William Lopez', email: 'william@student.pixlpluzportal.demo', role: 'student', cohortId: 'cohort-3', avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=William', skills: ['Ruby', 'Rails', 'Redis'], githubUrl: 'https://github.com/williamlopez', createdAt: '2024-04-01T00:00:00Z' },
  { id: 'student-21', name: 'Abigail Hernandez', email: 'abigail@student.pixlpluzportal.demo', role: 'student', cohortId: 'cohort-3', avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Abigail', skills: ['Elixir', 'Phoenix', 'LiveView'], githubUrl: 'https://github.com/abigailhernandez', createdAt: '2024-04-01T00:00:00Z' },
  { id: 'student-22', name: 'Michael Gonzalez', email: 'michael@student.pixlpluzportal.demo', role: 'student', cohortId: 'cohort-3', avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Michael', skills: ['Scala', 'Akka', 'Spark'], githubUrl: 'https://github.com/michaelgonzalez', createdAt: '2024-04-01T00:00:00Z' },
  { id: 'student-23', name: 'Emily Wilson', email: 'emily@student.pixlpluzportal.demo', role: 'student', cohortId: 'cohort-3', avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Emily', skills: ['Remix', 'Prisma', 'Tailwind'], githubUrl: 'https://github.com/emilywilson', createdAt: '2024-04-01T00:00:00Z' },
  { id: 'student-24', name: 'Daniel Moore', email: 'daniel@student.pixlpluzportal.demo', role: 'student', cohortId: 'cohort-3', avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Daniel', skills: ['Astro', 'Markdown', 'Content Management'], githubUrl: 'https://github.com/danielmoore', createdAt: '2024-04-01T00:00:00Z' },
]

// Cohorts
export const mockCohorts: Cohort[] = [
  { id: 'cohort-1', name: 'Winter 2024', startDate: '2024-02-01', endDate: '2024-05-31', status: 'completed', studentCount: 8, mentorIds: ['mentor-1', 'mentor-2'], workstreamIds: ['ws-dm', 'ws-swd', 'ws-mp', 'ws-ds', 'ws-cs', 'ws-3d'] },
  { id: 'cohort-2', name: 'Spring 2024', startDate: '2024-03-01', endDate: '2024-06-30', status: 'active', studentCount: 8, mentorIds: ['mentor-3', 'mentor-4'], workstreamIds: ['ws-dm', 'ws-swd', 'ws-mp', 'ws-ds', 'ws-cs', 'ws-3d'] },
  { id: 'cohort-3', name: 'Summer 2024', startDate: '2024-04-01', endDate: '2024-07-31', status: 'active', studentCount: 8, mentorIds: ['mentor-5', 'mentor-6'], workstreamIds: ['ws-dm', 'ws-swd', 'ws-mp', 'ws-ds', 'ws-cs', 'ws-3d'] },
]

// Workstreams — imported from workstream-data.ts (full syllabus, rubrics, tools, portfolio outputs)
export const mockWorkstreams = allWorkstreams

// Deliverables
export const mockDeliverables: Deliverable[] = [
  // proj-1 Component Library
  { id: 'del-1', projectId: 'proj-1', title: 'Project Setup', description: 'TypeScript, React, and Storybook initialised', dueDate: '2024-02-10', status: 'approved', submissionId: 'sub-1', order: 1 },
  { id: 'del-2', projectId: 'proj-1', title: 'Button Component', description: 'Reusable button with variants and states', dueDate: '2024-02-15', status: 'approved', submissionId: 'sub-2', order: 2 },
  { id: 'del-3', projectId: 'proj-1', title: 'Input Component', description: 'Form inputs with validation and error states', dueDate: '2024-02-20', status: 'submitted', submissionId: 'sub-3', order: 3 },
  { id: 'del-4', projectId: 'proj-1', title: 'Component Tests', description: 'Unit tests for all components', dueDate: '2024-02-25', status: 'pending', order: 4 },
  { id: 'del-5', projectId: 'proj-1', title: 'Storybook Docs', description: 'Full Storybook documentation', dueDate: '2024-03-01', status: 'pending', order: 5 },
  // proj-2 Next.js Dashboard
  { id: 'del-6', projectId: 'proj-2', title: 'Project Setup', description: 'Next.js 14 with TypeScript and Tailwind', dueDate: '2024-03-05', status: 'approved', submissionId: 'sub-4', order: 1 },
  { id: 'del-7', projectId: 'proj-2', title: 'Authentication', description: 'Login/signup flows with NextAuth.js', dueDate: '2024-03-12', status: 'approved', submissionId: 'sub-5', order: 2 },
  { id: 'del-8', projectId: 'proj-2', title: 'Dashboard Layout', description: 'Collapsible sidebar and responsive layout', dueDate: '2024-03-18', status: 'submitted', submissionId: 'sub-6', order: 3 },
  { id: 'del-9', projectId: 'proj-2', title: 'Data Visualisation', description: 'Charts and graphs with Recharts', dueDate: '2024-03-25', status: 'pending', order: 4 },
  // proj-3 REST API
  { id: 'del-10', projectId: 'proj-3', title: 'API Schema Design', description: 'Database schema and endpoint specs', dueDate: '2024-02-15', status: 'approved', submissionId: 'sub-7', order: 1 },
  { id: 'del-11', projectId: 'proj-3', title: 'Express Server', description: 'Initialised with TypeScript and middleware', dueDate: '2024-02-20', status: 'approved', submissionId: 'sub-8', order: 2 },
  { id: 'del-12', projectId: 'proj-3', title: 'CRUD Endpoints', description: 'Full CRUD operations for all resources', dueDate: '2024-03-01', status: 'pending', order: 3 },
  { id: 'del-13', projectId: 'proj-3', title: 'Auth Middleware', description: 'JWT-based authentication layer', dueDate: '2024-03-08', status: 'pending', order: 4 },
  // proj-5 Generative Art
  { id: 'del-14', projectId: 'proj-5', title: 'Canvas Environment', description: 'Responsive canvas with animation loop', dueDate: '2024-03-08', status: 'approved', submissionId: 'sub-10', order: 1 },
  { id: 'del-15', projectId: 'proj-5', title: 'Generative Algorithm', description: 'Particle system or fractal generation', dueDate: '2024-03-18', status: 'submitted', submissionId: 'sub-11', order: 2 },
  { id: 'del-16', projectId: 'proj-5', title: 'Export Feature', description: 'Export artwork as PNG/SVG', dueDate: '2024-03-30', status: 'pending', order: 3 },
  // proj-7 Product Design
  { id: 'del-17', projectId: 'proj-7', title: 'User Research', description: 'User interviews, personas, and journey maps', dueDate: '2024-03-12', status: 'approved', submissionId: 'sub-12', order: 1 },
  { id: 'del-18', projectId: 'proj-7', title: 'Wireframes', description: 'Low-fidelity wireframes in Figma', dueDate: '2024-03-19', status: 'submitted', submissionId: 'sub-13', order: 2 },
  { id: 'del-19', projectId: 'proj-7', title: 'Prototype', description: 'Interactive prototype in Figma', dueDate: '2024-03-30', status: 'pending', order: 3 },
  // proj-8 CI/CD
  { id: 'del-20', projectId: 'proj-8', title: 'Docker Setup', description: 'Multi-stage Dockerfile and docker-compose', dueDate: '2024-03-15', status: 'approved', submissionId: 'sub-14', order: 1 },
  { id: 'del-21', projectId: 'proj-8', title: 'GitHub Actions', description: 'Build, test, and deploy pipeline', dueDate: '2024-03-24', status: 'submitted', submissionId: 'sub-15', order: 2 },
]

// Projects – extended with status, progress, startDate, endDate, studentIds, brief, clientName, deliverables ref
export const mockProjects: Project[] = [
  {
    id: 'proj-1',
    name: 'Component Library',
    description: 'Build a reusable React component library with TypeScript and Storybook documentation.',
    brief: `## Overview\nYour goal is to build a production-grade React component library that other developers can drop into any project. This mirrors real-world design system work at companies like Airbnb (react-dates) and Shopify (Polaris).\n\n## Requirements\n- All components must be accessible (WCAG 2.1 AA)\n- Full TypeScript prop types\n- Storybook stories for every component\n- Vitest unit tests (>80% coverage)\n\n## Deliverable Order\nSetup → Button → Input → Tests → Docs`,
    clientName: 'Frontend Foundations',
    workstreamId: 'ws-swd',
    mentorId: 'mentor-1',
    studentIds: ['student-1'],
    order: 1,
    status: 'live',
    progress: 60,
    startDate: '2024-02-01',
    endDate: '2024-03-15',
    dueDate: '2024-03-15',
    estimatedHours: 20,
    learningOutcomes: ['Component architecture', 'TypeScript patterns', 'Documentation', 'Testing components'],
    deliverables: [],
    resources: [{ id: 'res-1', title: 'React Component Patterns', type: 'article', url: 'https://patterns.dev' }],
    clientFeedback: [
      { id: 'cf-1', author: 'Alex Rivera', authorRole: 'Mentor', content: 'Great progress on the component architecture. The button variants are clean and consistent. Keep up this quality for the remaining components.', rating: 4, createdAt: '2024-02-16T11:00:00Z' },
    ],
    activityLog: [
      { id: 'al-1', userId: 'student-1', userName: 'Emma Thompson', action: 'Submitted', detail: 'Input Component', createdAt: '2024-02-19T13:00:00Z' },
      { id: 'al-2', userId: 'mentor-1', userName: 'Alex Rivera', action: 'Approved', detail: 'Button Component', createdAt: '2024-02-16T11:00:00Z' },
      { id: 'al-3', userId: 'student-1', userName: 'Emma Thompson', action: 'Submitted', detail: 'Button Component', createdAt: '2024-02-15T15:00:00Z' },
    ],
  },
  {
    id: 'proj-2',
    name: 'Next.js Dashboard',
    description: 'Create a full-featured admin dashboard with authentication and data visualisation.',
    brief: `## Overview\nBuild a production-quality admin dashboard using Next.js 14 App Router. Think of this as a mini internal tool used by a real company.\n\n## Requirements\n- NextAuth.js credentials + OAuth\n- Recharts data visualisation (line, bar, pie)\n- Responsive layout with collapsible sidebar\n- Server components where appropriate\n\n## Stack\nNext.js 14 · TypeScript · Tailwind · shadcn/ui · Recharts · NextAuth`,
    clientName: 'Internal Tooling Co.',
    workstreamId: 'ws-swd',
    mentorId: 'mentor-1',
    studentIds: ['student-2'],
    order: 2,
    status: 'live',
    progress: 75,
    startDate: '2024-03-01',
    endDate: '2024-04-15',
    dueDate: '2024-04-15',
    estimatedHours: 30,
    learningOutcomes: ['Server components', 'Authentication flows', 'Data fetching patterns', 'Charts and graphs'],
    deliverables: [],
    clientFeedback: [
      { id: 'cf-2', author: 'Morgan Lee', authorRole: 'Mentor', content: 'The authentication implementation looks solid. The session management is correctly scoped. Next step: make sure the dashboard data is loaded server-side for performance.', rating: 5, createdAt: '2024-03-14T10:00:00Z' },
    ],
    activityLog: [
      { id: 'al-4', userId: 'student-2', userName: 'Liam Martinez', action: 'Submitted', detail: 'Dashboard Layout', createdAt: '2024-03-17T15:00:00Z' },
      { id: 'al-5', userId: 'mentor-3', userName: 'Morgan Lee', action: 'Approved', detail: 'Authentication', createdAt: '2024-03-14T10:00:00Z' },
    ],
  },
  {
    id: 'proj-3',
    name: 'REST API Design',
    description: 'Design and implement a RESTful API with Node.js, Express, and PostgreSQL.',
    brief: `## Overview\nBuild a fully documented REST API that could serve as the backend for a SaaS product. Emphasis on good API design, security, and test coverage.\n\n## Requirements\n- OpenAPI 3.0 specification\n- JWT authentication + refresh tokens\n- Input validation with Zod\n- Integration tests with Supertest\n\n## Stack\nNode.js · Express · TypeScript · PostgreSQL · Zod · Supertest`,
    clientName: 'Backend Engineering',
    workstreamId: 'ws-swd',
    mentorId: 'mentor-2',
    studentIds: ['student-3'],
    order: 1,
    status: 'live',
    progress: 50,
    startDate: '2024-02-08',
    endDate: '2024-03-20',
    dueDate: '2024-03-20',
    estimatedHours: 25,
    learningOutcomes: ['API design', 'Database modeling', 'Authentication', 'Error handling'],
    deliverables: [],
    clientFeedback: [],
    activityLog: [
      { id: 'al-6', userId: 'mentor-2', userName: 'Jordan Chen', action: 'Approved', detail: 'Express Server Setup', createdAt: '2024-02-21T10:00:00Z' },
    ],
  },
  {
    id: 'proj-4',
    name: 'Real-time Chat App',
    description: 'Build a real-time chat application with WebSockets, rooms, and message persistence.',
    brief: `## Overview\nCreate a Slack-style real-time chat application. This project tests your ability to handle bi-directional communication and state synchronisation.\n\n## Requirements\n- Multiple chat rooms\n- User presence indicators (online/offline)\n- Message history (last 100 messages per room)\n- File sharing support\n\n## Stack\nNext.js · Socket.io · MongoDB · Cloudinary (file uploads)`,
    clientName: 'Backend Engineering',
    workstreamId: 'ws-swd',
    mentorId: 'mentor-2',
    studentIds: ['student-4'],
    order: 2,
    status: 'live',
    progress: 40,
    startDate: '2024-03-03',
    endDate: '2024-04-20',
    dueDate: '2024-04-20',
    estimatedHours: 28,
    learningOutcomes: ['WebSocket protocol', 'Real-time events', 'Message persistence', 'Scaling'],
    deliverables: [],
    clientFeedback: [],
    activityLog: [],
  },
  {
    id: 'proj-5',
    name: 'Generative Art',
    description: 'Create algorithmic art with Canvas API and creative coding techniques.',
    brief: `## Overview\nExplore the intersection of code and art. Build a generative art system that creates unique, dynamic visuals driven by algorithms and user interaction.\n\n## Requirements\n- Particle system with physics simulation\n- Mouse/touch interactivity\n- Color palette system\n- Export as high-res PNG\n\n## Stack\nVanilla JS · Canvas API · dat.GUI (controls)`,
    clientName: 'Creative Coding',
    workstreamId: 'ws-mp',
    mentorId: 'mentor-3',
    studentIds: ['student-5'],
    order: 1,
    status: 'live',
    progress: 67,
    startDate: '2024-03-05',
    endDate: '2024-03-30',
    dueDate: '2024-03-30',
    estimatedHours: 18,
    learningOutcomes: ['Canvas API', 'Algorithms', 'Animation loops', 'Color theory'],
    deliverables: [],
    clientFeedback: [
      { id: 'cf-3', author: 'Morgan Lee', authorRole: 'Mentor', content: 'The particle system implementation is stunning! The physics feel natural and the performance is impressive. Really excited to see the export feature.', rating: 5, createdAt: '2024-03-18T12:00:00Z' },
    ],
    activityLog: [
      { id: 'al-7', userId: 'student-5', userName: 'Ava Williams', action: 'Submitted', detail: 'Generative Algorithm', createdAt: '2024-03-17T14:00:00Z' },
      { id: 'al-8', userId: 'mentor-3', userName: 'Morgan Lee', action: 'Approved', detail: 'Canvas Environment', createdAt: '2024-03-09T10:00:00Z' },
    ],
  },
  {
    id: 'proj-6',
    name: '3D Web Experience',
    description: 'Build an interactive 3D website using Three.js and React Three Fiber.',
    brief: `## Overview\nCreate an immersive 3D web experience that could serve as a portfolio piece or product landing page. Focus on performance and user delight.\n\n## Requirements\n- Orbit / scroll-driven camera controls\n- Custom GLSL shaders (at least one)\n- Responsive across devices\n- Lighthouse performance score >80\n\n## Stack\nReact Three Fiber · Drei · GSAP · Leva (debug panel)`,
    clientName: 'Creative Coding',
    workstreamId: 'ws-3d',
    mentorId: 'mentor-3',
    studentIds: ['student-6'],
    order: 2,
    status: 'live',
    progress: 25,
    startDate: '2024-03-20',
    endDate: '2024-04-25',
    dueDate: '2024-04-25',
    estimatedHours: 32,
    learningOutcomes: ['3D fundamentals', 'Three.js', 'Performance optimization', 'User interaction'],
    deliverables: [],
    clientFeedback: [],
    activityLog: [],
  },
  {
    id: 'proj-7',
    name: 'Product Redesign',
    description: 'Redesign an existing product with user research and modern UI/UX principles.',
    brief: `## Overview\nSelect a live product with known UX issues and redesign it end-to-end: from user research through to a polished interactive prototype.\n\n## Requirements\n- Minimum 5 user interviews\n- Heuristic evaluation of original product\n- High-fidelity mockups in Figma (light + dark)\n- Annotated interactive prototype\n\n## Deliverable Sequence\nResearch → Wireframes → Prototype → Design System`,
    clientName: 'Product Design',
    workstreamId: 'ws-dm',
    mentorId: 'mentor-5',
    studentIds: ['student-7'],
    order: 1,
    status: 'live',
    progress: 67,
    startDate: '2024-03-05',
    endDate: '2024-04-10',
    dueDate: '2024-04-10',
    estimatedHours: 22,
    learningOutcomes: ['User research', 'Wireframing', 'Prototyping', 'Design systems'],
    deliverables: [],
    clientFeedback: [
      { id: 'cf-4', author: 'Casey Park', authorRole: 'Mentor', content: 'The user research is thorough. Your personas feel real and the pain points are well-evidenced. Make sure the wireframes stay faithful to those insights.', rating: 4, createdAt: '2024-03-14T11:00:00Z' },
    ],
    activityLog: [
      { id: 'al-9', userId: 'student-7', userName: 'Sophia Davis', action: 'Submitted', detail: 'Wireframes', createdAt: '2024-03-19T15:00:00Z' },
      { id: 'al-10', userId: 'mentor-5', userName: 'Casey Park', action: 'Approved', detail: 'User Research', createdAt: '2024-03-14T11:00:00Z' },
    ],
  },
  {
    id: 'proj-8',
    name: 'CI/CD Pipeline',
    description: 'Set up a complete CI/CD pipeline with GitHub Actions, Docker, and cloud deployment.',
    brief: `## Overview\nBuild a real CI/CD pipeline for a sample Node.js application. Every push to main should automatically test, build, and deploy the application.\n\n## Requirements\n- GitHub Actions workflow (lint → test → build → deploy)\n- Docker multi-stage builds\n- Staging + production environments\n- Rollback capability\n\n## Stack\nGitHub Actions · Docker · Railway (or Fly.io) · Node.js sample app`,
    clientName: 'DevOps & Infrastructure',
    workstreamId: 'ws-cs',
    mentorId: 'mentor-4',
    studentIds: ['student-8'],
    order: 1,
    status: 'live',
    progress: 67,
    startDate: '2024-03-10',
    endDate: '2024-04-05',
    dueDate: '2024-04-05',
    estimatedHours: 20,
    learningOutcomes: ['Docker', 'GitHub Actions', 'Automated testing', 'Deployment strategies'],
    deliverables: [],
    clientFeedback: [],
    activityLog: [
      { id: 'al-11', userId: 'student-8', userName: 'Mason Wilson', action: 'Submitted', detail: 'GitHub Actions Pipeline', createdAt: '2024-03-24T15:00:00Z' },
      { id: 'al-12', userId: 'mentor-4', userName: 'Taylor Kim', action: 'Approved', detail: 'Docker Setup', createdAt: '2024-03-16T10:00:00Z' },
    ],
  },
  {
    id: 'proj-9',
    name: 'Personal Portfolio',
    description: 'Design and build your personal portfolio website to showcase your work.',
    brief: `## Overview\nYour portfolio is often the first thing a recruiter sees. Build something you are proud to share.\n\n## Requirements\n- Homepage with hero and project showcase\n- Individual project case study pages\n- Contact form (Resend or Nodemailer)\n- Core Web Vitals: all green\n\n## Bonus\nAnimate page transitions · Dark/light mode · Blog section`,
    clientName: 'Capstone Projects',
    workstreamId: 'ws-ds',
    mentorId: 'mentor-5',
    studentIds: ['student-9'],
    order: 1,
    status: 'live',
    progress: 33,
    startDate: '2024-04-05',
    endDate: '2024-05-01',
    dueDate: '2024-05-01',
    estimatedHours: 25,
    learningOutcomes: ['Personal branding', 'Content strategy', 'SEO', 'Performance'],
    deliverables: [],
    clientFeedback: [
      { id: 'cf-5', author: 'Casey Park', authorRole: 'Mentor', content: 'The Figma designs are excellent! The dark theme and project card layout look professional. Looking forward to seeing this built out.', rating: 5, createdAt: '2024-04-12T09:00:00Z' },
    ],
    activityLog: [
      { id: 'al-13', userId: 'mentor-5', userName: 'Casey Park', action: 'Approved', detail: 'Portfolio Design', createdAt: '2024-04-12T09:00:00Z' },
    ],
  },
  {
    id: 'proj-10',
    name: 'Capstone Project',
    description: 'Build a full-stack application showcasing all the skills you have developed.',
    brief: `## Overview\nYour capstone is the culmination of everything you have learned. Build something you would genuinely use or that solves a real problem you care about.\n\n## Requirements\n- Full-stack (frontend + backend + database)\n- Authentication and authorisation\n- Deploy to production (Vercel + Railway or similar)\n- 5-minute demo video\n- Written case study\n\n## Timeline\nSpec → Architecture → Build → Polish → Present`,
    clientName: 'Capstone Projects',
    workstreamId: 'ws-ds',
    mentorId: 'mentor-6',
    studentIds: ['student-10'],
    order: 2,
    status: 'archived',
    progress: 100,
    startDate: '2024-04-01',
    endDate: '2024-06-01',
    dueDate: '2024-06-01',
    estimatedHours: 50,
    learningOutcomes: ['Project planning', 'Full-stack integration', 'User testing', 'Presentation skills'],
    deliverables: [],
    clientFeedback: [
      { id: 'cf-6', author: 'Jamie Patel', authorRole: 'Mentor', content: 'Outstanding capstone! The collaborative task manager is feature-complete, well-tested, and deployed. The presentation was confident and the demo video was excellent. This is portfolio-ready work.', rating: 5, createdAt: '2024-06-03T10:00:00Z' },
    ],
    activityLog: [
      { id: 'al-14', userId: 'student-10', userName: 'Lucas Anderson', action: 'Completed', detail: 'Capstone Project', createdAt: '2024-06-01T17:00:00Z' },
    ],
  },
]

// Tasks
export const mockTasks: Task[] = [
  // Component Library
  { id: 'task-1', title: 'Setup Project Structure', description: 'Initialise the project with TypeScript, React, and Storybook', projectId: 'proj-1', assignedTo: 'student-1', status: 'completed', priority: 'high', dueDate: '2024-02-10', estimatedHours: 4, actualHours: 5, createdAt: '2024-02-01T10:00:00Z', updatedAt: '2024-02-10T15:00:00Z', tags: ['setup', 'tooling'] },
  { id: 'task-2', title: 'Build Button Component', description: 'Create a reusable button component with variants and states', projectId: 'proj-1', assignedTo: 'student-1', status: 'completed', priority: 'high', dueDate: '2024-02-15', estimatedHours: 6, actualHours: 7, createdAt: '2024-02-11T10:00:00Z', updatedAt: '2024-02-15T16:00:00Z', tags: ['components'] },
  { id: 'task-3', title: 'Build Input Component', description: 'Create form input components with validation', projectId: 'proj-1', assignedTo: 'student-1', status: 'review', priority: 'medium', dueDate: '2024-02-20', estimatedHours: 8, createdAt: '2024-02-16T10:00:00Z', updatedAt: '2024-02-19T14:00:00Z', tags: ['components', 'forms'] },
  { id: 'task-4', title: 'Write Component Tests', description: 'Add unit tests for all components', projectId: 'proj-1', assignedTo: 'student-1', status: 'in-progress', priority: 'medium', dueDate: '2024-02-25', estimatedHours: 10, createdAt: '2024-02-20T10:00:00Z', updatedAt: '2024-02-22T11:00:00Z', tags: ['testing'] },
  { id: 'task-5', title: 'Setup Storybook', description: 'Configure Storybook for component documentation', projectId: 'proj-1', assignedTo: 'student-1', status: 'todo', priority: 'low', dueDate: '2024-03-01', estimatedHours: 5, createdAt: '2024-02-23T10:00:00Z', updatedAt: '2024-02-23T10:00:00Z', tags: ['documentation'] },
  // Next.js Dashboard
  { id: 'task-6', title: 'Setup Next.js Project', description: 'Initialise Next.js 14 with TypeScript and Tailwind', projectId: 'proj-2', assignedTo: 'student-2', status: 'completed', priority: 'high', dueDate: '2024-03-05', estimatedHours: 3, actualHours: 3, createdAt: '2024-03-01T10:00:00Z', updatedAt: '2024-03-05T14:00:00Z', tags: ['setup'] },
  { id: 'task-7', title: 'Implement Authentication', description: 'Add authentication with NextAuth.js', projectId: 'proj-2', assignedTo: 'student-2', status: 'completed', priority: 'high', dueDate: '2024-03-12', estimatedHours: 8, actualHours: 10, createdAt: '2024-03-06T10:00:00Z', updatedAt: '2024-03-12T18:00:00Z', tags: ['auth', 'security'] },
  { id: 'task-8', title: 'Build Dashboard Layout', description: 'Create the main dashboard layout with sidebar and navigation', projectId: 'proj-2', assignedTo: 'student-2', status: 'review', priority: 'high', dueDate: '2024-03-18', estimatedHours: 6, createdAt: '2024-03-13T10:00:00Z', updatedAt: '2024-03-17T16:00:00Z', tags: ['ui', 'layout'] },
  { id: 'task-9', title: 'Add Data Visualisation', description: 'Implement charts and graphs using Recharts', projectId: 'proj-2', assignedTo: 'student-2', status: 'in-progress', priority: 'medium', dueDate: '2024-03-25', estimatedHours: 10, createdAt: '2024-03-18T10:00:00Z', updatedAt: '2024-03-20T15:00:00Z', tags: ['charts', 'data'] },
  { id: 'task-10', title: 'Implement User Settings', description: 'Create user profile and settings page', projectId: 'proj-2', assignedTo: 'student-2', status: 'todo', priority: 'low', dueDate: '2024-04-01', estimatedHours: 6, createdAt: '2024-03-21T10:00:00Z', updatedAt: '2024-03-21T10:00:00Z', tags: ['profile', 'settings'] },
  // REST API
  { id: 'task-11', title: 'Design API Schema', description: 'Design database schema and API endpoints', projectId: 'proj-3', assignedTo: 'student-3', status: 'completed', priority: 'high', dueDate: '2024-02-15', estimatedHours: 5, actualHours: 6, createdAt: '2024-02-08T10:00:00Z', updatedAt: '2024-02-15T17:00:00Z', tags: ['design', 'database'] },
  { id: 'task-12', title: 'Setup Express Server', description: 'Initialise Express.js with TypeScript', projectId: 'proj-3', assignedTo: 'student-3', status: 'completed', priority: 'high', dueDate: '2024-02-20', estimatedHours: 4, actualHours: 4, createdAt: '2024-02-16T10:00:00Z', updatedAt: '2024-02-20T15:00:00Z', tags: ['setup', 'backend'] },
  { id: 'task-13', title: 'Implement CRUD Operations', description: 'Create endpoints for Create, Read, Update, Delete', projectId: 'proj-3', assignedTo: 'student-3', status: 'in-progress', priority: 'high', dueDate: '2024-03-01', estimatedHours: 10, createdAt: '2024-02-21T10:00:00Z', updatedAt: '2024-02-25T14:00:00Z', tags: ['api', 'crud'] },
  { id: 'task-14', title: 'Add Authentication Middleware', description: 'Implement JWT-based authentication', projectId: 'proj-3', assignedTo: 'student-3', status: 'todo', priority: 'high', dueDate: '2024-03-08', estimatedHours: 8, createdAt: '2024-02-26T10:00:00Z', updatedAt: '2024-02-26T10:00:00Z', tags: ['auth', 'middleware'] },
  { id: 'task-15', title: 'Write API Tests', description: 'Add integration tests for all endpoints', projectId: 'proj-3', assignedTo: 'student-3', status: 'todo', priority: 'medium', dueDate: '2024-03-15', estimatedHours: 8, createdAt: '2024-02-27T10:00:00Z', updatedAt: '2024-02-27T10:00:00Z', tags: ['testing'] },
  // Chat App
  { id: 'task-16', title: 'Setup WebSocket Server', description: 'Initialise Socket.io server', projectId: 'proj-4', assignedTo: 'student-4', status: 'completed', priority: 'high', dueDate: '2024-03-10', estimatedHours: 5, actualHours: 6, createdAt: '2024-03-03T10:00:00Z', updatedAt: '2024-03-10T16:00:00Z', tags: ['websocket', 'setup'] },
  { id: 'task-17', title: 'Implement Chat UI', description: 'Build the chat interface with React', projectId: 'proj-4', assignedTo: 'student-4', status: 'in-progress', priority: 'high', dueDate: '2024-03-20', estimatedHours: 10, createdAt: '2024-03-11T10:00:00Z', updatedAt: '2024-03-18T14:00:00Z', tags: ['ui', 'chat'] },
  { id: 'task-18', title: 'Add Message Persistence', description: 'Store messages in MongoDB', projectId: 'proj-4', assignedTo: 'student-4', status: 'todo', priority: 'medium', dueDate: '2024-03-28', estimatedHours: 7, createdAt: '2024-03-19T10:00:00Z', updatedAt: '2024-03-19T10:00:00Z', tags: ['database', 'persistence'] },
  // Generative Art
  { id: 'task-19', title: 'Setup Canvas Environment', description: 'Create canvas boilerplate with animation loop', projectId: 'proj-5', assignedTo: 'student-5', status: 'completed', priority: 'high', dueDate: '2024-03-08', estimatedHours: 3, actualHours: 3, createdAt: '2024-03-05T10:00:00Z', updatedAt: '2024-03-08T14:00:00Z', tags: ['canvas', 'setup'] },
  { id: 'task-20', title: 'Create Generative Algorithm', description: 'Implement particle system or fractal generation', projectId: 'proj-5', assignedTo: 'student-5', status: 'review', priority: 'high', dueDate: '2024-03-18', estimatedHours: 8, createdAt: '2024-03-09T10:00:00Z', updatedAt: '2024-03-17T15:00:00Z', tags: ['algorithm', 'creative'] },
  { id: 'task-21', title: 'Setup Three.js Scene', description: 'Create Three.js scene with lighting and camera', projectId: 'proj-6', assignedTo: 'student-6', status: 'in-progress', priority: 'high', dueDate: '2024-03-30', estimatedHours: 6, createdAt: '2024-03-20T10:00:00Z', updatedAt: '2024-03-25T14:00:00Z', tags: ['3d', 'threejs'] },
  { id: 'task-22', title: 'Add 3D Models', description: 'Import and display 3D models in the scene', projectId: 'proj-6', assignedTo: 'student-6', status: 'todo', priority: 'high', dueDate: '2024-04-10', estimatedHours: 10, createdAt: '2024-03-28T10:00:00Z', updatedAt: '2024-03-28T10:00:00Z', tags: ['3d', 'models'] },
  // Product Design
  { id: 'task-23', title: 'Conduct User Research', description: 'Conduct 8 user interviews and synthesise insights', projectId: 'proj-7', assignedTo: 'student-7', status: 'completed', priority: 'high', dueDate: '2024-03-12', estimatedHours: 10, actualHours: 11, createdAt: '2024-03-05T10:00:00Z', updatedAt: '2024-03-12T16:00:00Z', tags: ['research', 'ux'] },
  { id: 'task-24', title: 'Create Wireframes', description: 'Design low-fidelity wireframes in Figma', projectId: 'proj-7', assignedTo: 'student-7', status: 'review', priority: 'high', dueDate: '2024-03-19', estimatedHours: 8, createdAt: '2024-03-13T10:00:00Z', updatedAt: '2024-03-18T15:00:00Z', tags: ['wireframes', 'figma'] },
  { id: 'task-25', title: 'Build Interactive Prototype', description: 'Create high-fidelity interactive prototype', projectId: 'proj-7', assignedTo: 'student-7', status: 'todo', priority: 'high', dueDate: '2024-03-30', estimatedHours: 12, createdAt: '2024-03-20T10:00:00Z', updatedAt: '2024-03-20T10:00:00Z', tags: ['prototype'] },
  // CI/CD Pipeline
  { id: 'task-26', title: 'Setup Docker', description: 'Create Dockerfile with multi-stage builds', projectId: 'proj-8', assignedTo: 'student-8', status: 'completed', priority: 'high', dueDate: '2024-03-15', estimatedHours: 6, actualHours: 7, createdAt: '2024-03-10T10:00:00Z', updatedAt: '2024-03-15T15:00:00Z', tags: ['docker', 'devops'] },
  { id: 'task-27', title: 'Configure GitHub Actions', description: 'Setup CI/CD workflow with GitHub Actions', projectId: 'proj-8', assignedTo: 'student-8', status: 'review', priority: 'high', dueDate: '2024-03-24', estimatedHours: 8, createdAt: '2024-03-16T10:00:00Z', updatedAt: '2024-03-23T16:00:00Z', tags: ['ci-cd', 'github'] },
  { id: 'task-28', title: 'Deploy to Cloud', description: 'Deploy application to cloud provider', projectId: 'proj-8', assignedTo: 'student-8', status: 'todo', priority: 'high', dueDate: '2024-04-08', estimatedHours: 6, createdAt: '2024-03-25T10:00:00Z', updatedAt: '2024-03-25T10:00:00Z', tags: ['deployment'] },
  // Personal Portfolio
  { id: 'task-29', title: 'Design Portfolio', description: 'Design portfolio site in Figma', projectId: 'proj-9', assignedTo: 'student-9', status: 'completed', priority: 'high', dueDate: '2024-04-10', estimatedHours: 8, actualHours: 9, createdAt: '2024-04-05T10:00:00Z', updatedAt: '2024-04-10T16:00:00Z', tags: ['design', 'figma'] },
  { id: 'task-30', title: 'Build Portfolio Site', description: 'Implement the portfolio design with Next.js', projectId: 'proj-9', assignedTo: 'student-9', status: 'in-progress', priority: 'high', dueDate: '2024-04-22', estimatedHours: 15, createdAt: '2024-04-11T10:00:00Z', updatedAt: '2024-04-20T14:00:00Z', tags: ['development'] },
  // Capstone
  { id: 'task-31', title: 'Define Project Scope', description: 'Write project spec, tech stack, and roadmap', projectId: 'proj-10', assignedTo: 'student-10', status: 'completed', priority: 'high', dueDate: '2024-04-15', estimatedHours: 6, actualHours: 6, createdAt: '2024-04-01T10:00:00Z', updatedAt: '2024-04-15T17:00:00Z', tags: ['planning'] },
  { id: 'task-32', title: 'Build Core Features', description: 'Implement all primary application features', projectId: 'proj-10', assignedTo: 'student-10', status: 'completed', priority: 'high', dueDate: '2024-05-15', estimatedHours: 30, actualHours: 35, createdAt: '2024-04-16T10:00:00Z', updatedAt: '2024-05-15T18:00:00Z', tags: ['development'] },
  { id: 'task-33', title: 'Final Presentation', description: 'Prepare and record 5-minute demo video', projectId: 'proj-10', assignedTo: 'student-10', status: 'completed', priority: 'medium', dueDate: '2024-05-30', estimatedHours: 8, actualHours: 8, createdAt: '2024-05-20T10:00:00Z', updatedAt: '2024-05-30T17:00:00Z', tags: ['presentation'] },
]

// Submissions
export const mockSubmissions: Submission[] = [
  { id: 'sub-1', taskId: 'task-1', projectId: 'proj-1', deliverableId: 'del-1', studentId: 'student-1', status: 'approved', submittedAt: '2024-02-10T14:00:00Z', content: 'Completed project setup with TypeScript, React, and Storybook. All configurations are working correctly with proper path aliases and build scripts.', githubUrl: 'https://github.com/student1/component-library', grade: 95, reviewId: 'rev-1', createdAt: '2024-02-10T14:00:00Z', updatedAt: '2024-02-12T10:00:00Z' },
  { id: 'sub-2', taskId: 'task-2', projectId: 'proj-1', deliverableId: 'del-2', studentId: 'student-1', status: 'approved', submittedAt: '2024-02-15T15:00:00Z', content: 'Built a comprehensive button component with multiple variants (primary, secondary, outline, ghost), sizes (sm, md, lg), and states (default, hover, disabled, loading). Includes proper TypeScript types, ARIA attributes, and keyboard navigation support.', githubUrl: 'https://github.com/student1/component-library', grade: 92, reviewId: 'rev-2', createdAt: '2024-02-15T15:00:00Z', updatedAt: '2024-02-16T11:00:00Z' },
  { id: 'sub-3', taskId: 'task-3', projectId: 'proj-1', deliverableId: 'del-3', studentId: 'student-1', status: 'submitted', submittedAt: '2024-02-19T13:00:00Z', content: 'Created input component with validation support, error states, and various input types (text, email, password, number). Implemented controlled component pattern with forwardRef for form library compatibility.', githubUrl: 'https://github.com/student1/component-library', createdAt: '2024-02-19T13:00:00Z', updatedAt: '2024-02-19T13:00:00Z' },
  { id: 'sub-4', taskId: 'task-6', projectId: 'proj-2', deliverableId: 'del-6', studentId: 'student-2', status: 'approved', submittedAt: '2024-03-05T13:00:00Z', content: 'Initialised Next.js 14 project with TypeScript, Tailwind CSS, and ESLint. Set up proper folder structure with app router, configured path aliases, and added Husky pre-commit hooks.', githubUrl: 'https://github.com/student2/dashboard', grade: 100, reviewId: 'rev-3', createdAt: '2024-03-05T13:00:00Z', updatedAt: '2024-03-06T09:00:00Z' },
  { id: 'sub-5', taskId: 'task-7', projectId: 'proj-2', deliverableId: 'del-7', studentId: 'student-2', status: 'approved', submittedAt: '2024-03-12T17:00:00Z', content: 'Implemented authentication using NextAuth.js with credentials provider and GitHub OAuth. Added login/signup pages, session management, protected routes via middleware, and proper error handling.', githubUrl: 'https://github.com/student2/dashboard', grade: 88, reviewId: 'rev-4', createdAt: '2024-03-12T17:00:00Z', updatedAt: '2024-03-14T10:00:00Z' },
  { id: 'sub-6', taskId: 'task-8', projectId: 'proj-2', deliverableId: 'del-8', studentId: 'student-2', status: 'submitted', submittedAt: '2024-03-17T15:00:00Z', content: 'Built responsive dashboard layout with collapsible sidebar, top navigation bar, and main content area. Used shadcn/ui components throughout. Sidebar collapses to icon-only on mobile. All routes are protected.', githubUrl: 'https://github.com/student2/dashboard', createdAt: '2024-03-17T15:00:00Z', updatedAt: '2024-03-17T15:00:00Z' },
  { id: 'sub-7', taskId: 'task-11', projectId: 'proj-3', deliverableId: 'del-10', studentId: 'student-3', status: 'approved', submittedAt: '2024-02-15T16:00:00Z', content: 'Designed comprehensive database schema with proper relationships, indexes, and constraints. Created ERD diagram in dbdiagram.io and OpenAPI 3.0 spec for all endpoints. Includes soft delete support and audit timestamps.', githubUrl: 'https://github.com/student3/rest-api', grade: 94, reviewId: 'rev-5', createdAt: '2024-02-15T16:00:00Z', updatedAt: '2024-02-17T09:00:00Z' },
  { id: 'sub-8', taskId: 'task-12', projectId: 'proj-3', deliverableId: 'del-11', studentId: 'student-3', status: 'approved', submittedAt: '2024-02-20T14:00:00Z', content: 'Set up Express.js server with TypeScript, configured middleware for CORS, body parsing, and error handling. Project structure follows MVC pattern with separate router, controller, and service layers.', githubUrl: 'https://github.com/student3/rest-api', grade: 96, reviewId: 'rev-6', createdAt: '2024-02-20T14:00:00Z', updatedAt: '2024-02-21T10:00:00Z' },
  { id: 'sub-9', taskId: 'task-16', projectId: 'proj-4', studentId: 'student-4', status: 'approved', submittedAt: '2024-03-10T15:00:00Z', content: 'Initialised Socket.io server with connection handling, room management, and typed event listeners. Implemented proper error handling, reconnection logic with exponential backoff, and heartbeat mechanism.', githubUrl: 'https://github.com/student4/chat-app', grade: 91, reviewId: 'rev-7', createdAt: '2024-03-10T15:00:00Z', updatedAt: '2024-03-12T09:00:00Z' },
  { id: 'sub-10', taskId: 'task-19', projectId: 'proj-5', deliverableId: 'del-14', studentId: 'student-5', status: 'approved', submittedAt: '2024-03-08T13:00:00Z', content: 'Created canvas environment with proper setup and animation loop using requestAnimationFrame. Implemented responsive canvas sizing with ResizeObserver, devicePixelRatio support for retina displays, and clean teardown on unmount.', githubUrl: 'https://github.com/student5/generative-art', liveUrl: 'https://student5-art.vercel.app', grade: 98, reviewId: 'rev-8', createdAt: '2024-03-08T13:00:00Z', updatedAt: '2024-03-09T10:00:00Z' },
  { id: 'sub-11', taskId: 'task-20', projectId: 'proj-5', deliverableId: 'del-15', studentId: 'student-5', status: 'submitted', submittedAt: '2024-03-17T14:00:00Z', content: 'Implemented particle system with Newtonian physics simulation (gravity, friction, collision), mouse interaction (attract/repel), and HSL colour gradients based on particle velocity. Consistently achieving 60fps with 5,000+ particles.', githubUrl: 'https://github.com/student5/generative-art', liveUrl: 'https://student5-art.vercel.app', createdAt: '2024-03-17T14:00:00Z', updatedAt: '2024-03-17T14:00:00Z' },
  { id: 'sub-12', taskId: 'task-23', projectId: 'proj-7', deliverableId: 'del-17', studentId: 'student-7', status: 'approved', submittedAt: '2024-03-12T16:00:00Z', content: 'Conducted 8 user interviews and created 3 user personas, 2 journey maps, and detailed pain point analysis. Synthesised findings into 12 actionable design insights. Included competitive analysis of 4 similar products.', grade: 90, reviewId: 'rev-9', createdAt: '2024-03-12T16:00:00Z', updatedAt: '2024-03-14T11:00:00Z' },
  { id: 'sub-13', taskId: 'task-24', projectId: 'proj-7', deliverableId: 'del-18', studentId: 'student-7', status: 'submitted', submittedAt: '2024-03-19T15:00:00Z', content: 'Created low-fidelity wireframes for all 12 key screens in Figma. Includes information architecture, user flow documentation, and annotated decisions explaining each design choice.', createdAt: '2024-03-19T15:00:00Z', updatedAt: '2024-03-19T15:00:00Z' },
  { id: 'sub-14', taskId: 'task-26', projectId: 'proj-8', deliverableId: 'del-20', studentId: 'student-8', status: 'approved', submittedAt: '2024-03-15T14:00:00Z', content: 'Created Dockerfile with multi-stage builds (build → runtime) reducing final image size by 65%. Set up docker-compose with services for app, PostgreSQL, and Redis. Includes health checks and proper volume configuration.', githubUrl: 'https://github.com/student8/cicd-pipeline', grade: 93, reviewId: 'rev-10', createdAt: '2024-03-15T14:00:00Z', updatedAt: '2024-03-16T10:00:00Z' },
  { id: 'sub-15', taskId: 'task-27', projectId: 'proj-8', deliverableId: 'del-21', studentId: 'student-8', status: 'submitted', submittedAt: '2024-03-24T15:00:00Z', content: 'Configured GitHub Actions workflow with lint → test → build → deploy stages. Implemented pnpm caching for 40% faster builds. Separate staging (PR) and production (main) deployment targets with manual approval gate for prod.', githubUrl: 'https://github.com/student8/cicd-pipeline', createdAt: '2024-03-24T15:00:00Z', updatedAt: '2024-03-24T15:00:00Z' },
  { id: 'sub-16', taskId: 'task-29', projectId: 'proj-9', studentId: 'student-9', status: 'approved', submittedAt: '2024-04-10T16:00:00Z', content: 'Designed portfolio site in Figma with dark theme, smooth scroll animations, and project showcase cards. Includes mobile-responsive layouts for all screens. Dark/light mode toggle. Three custom typefaces with variable font.', grade: 95, reviewId: 'rev-11', createdAt: '2024-04-10T16:00:00Z', updatedAt: '2024-04-12T09:00:00Z' },
  { id: 'sub-17', taskId: 'task-31', projectId: 'proj-10', studentId: 'student-10', status: 'approved', submittedAt: '2024-04-15T17:00:00Z', content: 'Defined capstone scope: a collaborative task management app with real-time updates. Tech stack: Next.js 14, Prisma, PostgreSQL, tRPC, Pusher. Created 3-month roadmap with weekly milestones, feature prioritisation matrix, and risk register.', grade: 92, reviewId: 'rev-12', createdAt: '2024-04-15T17:00:00Z', updatedAt: '2024-04-17T10:00:00Z' },
  { id: 'sub-18', taskId: 'task-33', projectId: 'proj-10', studentId: 'student-10', status: 'approved', submittedAt: '2024-05-30T17:00:00Z', content: 'Delivered 5-minute demo video showcasing all core features. Live deployment at capstone.vercel.app. Written case study covering architecture decisions, challenges, and retrospective. Presented to full cohort.', grade: 97, reviewId: 'rev-13', createdAt: '2024-05-30T17:00:00Z', updatedAt: '2024-05-31T09:00:00Z' },
]

// Reviews
export const mockReviews: Review[] = [
  { id: 'rev-1', submissionId: 'sub-1', projectId: 'proj-1', deliverableId: 'del-1', reviewerId: 'mentor-1', status: 'completed', decision: 'approved', feedback: 'Excellent work on the project setup! The configuration is clean and well-organised. All tooling is properly configured with sensible defaults. The path aliases will save everyone a lot of time.', strengths: ['Clean project structure', 'Proper TypeScript configuration', 'Good documentation in README'], improvements: ['Consider adding pre-commit hooks with Husky', 'Add more scripts to package.json'], grade: 95, rubricScores: [{ category: 'Code Quality', weight: 30, score: 5, maxScore: 5 }, { category: 'Technical Correctness', weight: 30, score: 5, maxScore: 5 }, { category: 'Documentation', weight: 20, score: 4, maxScore: 5 }, { category: 'Best Practices', weight: 20, score: 5, maxScore: 5 }], slaDeadline: '2024-02-13T14:00:00Z', startedAt: '2024-02-11T09:00:00Z', completedAt: '2024-02-12T10:00:00Z', createdAt: '2024-02-11T09:00:00Z', updatedAt: '2024-02-12T10:00:00Z' },
  { id: 'rev-2', submissionId: 'sub-2', projectId: 'proj-1', deliverableId: 'del-2', reviewerId: 'mentor-1', status: 'completed', decision: 'approved', feedback: 'Great button component! Well-structured with proper variants and accessibility. The forwardRef implementation is spot on. Minor improvements needed in prop validation.', strengths: ['Excellent variant system', 'Good accessibility practices', 'Clean TypeScript types', 'Responsive to keyboard navigation'], improvements: ['Add prop validation for edge cases', 'Consider adding a loading state', 'Add more unit tests for the disabled state'], grade: 92, rubricScores: [{ category: 'Code Quality', weight: 30, score: 4, maxScore: 5 }, { category: 'Technical Correctness', weight: 30, score: 5, maxScore: 5 }, { category: 'Accessibility', weight: 20, score: 5, maxScore: 5 }, { category: 'Testing', weight: 20, score: 4, maxScore: 5 }], slaDeadline: '2024-02-17T15:00:00Z', completedAt: '2024-02-16T11:00:00Z', createdAt: '2024-02-15T17:00:00Z', updatedAt: '2024-02-16T11:00:00Z' },
  { id: 'rev-3', submissionId: 'sub-4', projectId: 'proj-2', deliverableId: 'del-6', reviewerId: 'mentor-3', status: 'completed', decision: 'approved', feedback: 'Perfect project setup! Everything is configured correctly and follows Next.js best practices. Outstanding work — especially the Husky pre-commit hooks, that shows initiative.', strengths: ['Flawless configuration', 'Optimal folder structure', 'Excellent tooling setup', 'Proactive addition of pre-commit hooks'], improvements: [], grade: 100, rubricScores: [{ category: 'Code Quality', weight: 30, score: 5, maxScore: 5 }, { category: 'Technical Correctness', weight: 30, score: 5, maxScore: 5 }, { category: 'Documentation', weight: 20, score: 5, maxScore: 5 }, { category: 'Best Practices', weight: 20, score: 5, maxScore: 5 }], slaDeadline: '2024-03-07T13:00:00Z', completedAt: '2024-03-06T09:00:00Z', createdAt: '2024-03-05T15:00:00Z', updatedAt: '2024-03-06T09:00:00Z' },
  { id: 'rev-4', submissionId: 'sub-5', projectId: 'proj-2', deliverableId: 'del-7', reviewerId: 'mentor-3', status: 'completed', decision: 'revision-requested', feedback: 'Good authentication implementation! The core flow works well but there are security gaps that must be addressed before this can be approved. Rate limiting is non-negotiable for a login endpoint.', strengths: ['Working OAuth flow', 'Good session management', 'Clean UI for login/signup'], improvements: ['Add rate limiting to login endpoint (required)', 'Implement password strength validation', 'Add email verification for new accounts', 'Improve error messages (avoid leaking user existence)'], grade: 72, rubricScores: [{ category: 'Code Quality', weight: 30, score: 4, maxScore: 5 }, { category: 'Security', weight: 30, score: 3, maxScore: 5 }, { category: 'Technical Correctness', weight: 20, score: 4, maxScore: 5 }, { category: 'UX', weight: 20, score: 4, maxScore: 5 }], slaDeadline: '2024-03-14T17:00:00Z', completedAt: '2024-03-14T10:00:00Z', createdAt: '2024-03-13T09:00:00Z', updatedAt: '2024-03-14T10:00:00Z' },
  { id: 'rev-5', submissionId: 'sub-7', projectId: 'proj-3', deliverableId: 'del-10', reviewerId: 'mentor-2', status: 'completed', decision: 'approved', feedback: 'Excellent database design! The schema is well-normalised with proper relationships. ERD is clear and the OpenAPI spec is comprehensive. The soft delete support shows real-world thinking.', strengths: ['Well-normalised schema', 'Proper indexing strategy', 'Clear ERD documentation', 'Good constraint definitions', 'OpenAPI 3.0 spec included'], improvements: ['Consider adding audit log triggers at DB level', 'Add pagination parameters to list endpoints in spec'], grade: 94, rubricScores: [{ category: 'Schema Design', weight: 30, score: 5, maxScore: 5 }, { category: 'Documentation', weight: 25, score: 5, maxScore: 5 }, { category: 'Best Practices', weight: 25, score: 5, maxScore: 5 }, { category: 'Completeness', weight: 20, score: 4, maxScore: 5 }], slaDeadline: '2024-02-17T16:00:00Z', completedAt: '2024-02-17T09:00:00Z', createdAt: '2024-02-16T10:00:00Z', updatedAt: '2024-02-17T09:00:00Z' },
  { id: 'rev-6', submissionId: 'sub-8', projectId: 'proj-3', deliverableId: 'del-11', reviewerId: 'mentor-2', status: 'completed', decision: 'approved', feedback: 'Great Express setup! The MVC structure is solid and middleware configuration is proper. Very well organised — the service layer abstraction will pay dividends as the codebase grows.', strengths: ['Clean MVC structure', 'Proper middleware ordering', 'Good error propagation', 'TypeScript integration is clean'], improvements: ['Add API versioning prefix (e.g. /v1/)', 'Consider request validation middleware with Zod'], grade: 96, rubricScores: [{ category: 'Architecture', weight: 35, score: 5, maxScore: 5 }, { category: 'Code Quality', weight: 30, score: 5, maxScore: 5 }, { category: 'Best Practices', weight: 20, score: 5, maxScore: 5 }, { category: 'Documentation', weight: 15, score: 4, maxScore: 5 }], slaDeadline: '2024-02-22T14:00:00Z', completedAt: '2024-02-21T10:00:00Z', createdAt: '2024-02-20T16:00:00Z', updatedAt: '2024-02-21T10:00:00Z' },
  { id: 'rev-7', submissionId: 'sub-9', projectId: 'proj-4', reviewerId: 'mentor-4', status: 'completed', decision: 'approved', feedback: 'Solid WebSocket implementation! Connection handling is robust and typed events are a nice touch. The exponential backoff on reconnect is production-quality thinking.', strengths: ['Robust connection handling', 'Typed event system', 'Exponential backoff reconnect', 'Room management works well'], improvements: ['Add connection authentication (JWT in handshake)', 'Log disconnect reasons for debugging'], grade: 91, rubricScores: [{ category: 'Technical Correctness', weight: 35, score: 5, maxScore: 5 }, { category: 'Code Quality', weight: 30, score: 4, maxScore: 5 }, { category: 'Error Handling', weight: 20, score: 5, maxScore: 5 }, { category: 'Best Practices', weight: 15, score: 4, maxScore: 5 }], slaDeadline: '2024-03-12T15:00:00Z', completedAt: '2024-03-12T09:00:00Z', createdAt: '2024-03-11T10:00:00Z', updatedAt: '2024-03-12T09:00:00Z' },
  { id: 'rev-8', submissionId: 'sub-10', projectId: 'proj-5', deliverableId: 'del-14', reviewerId: 'mentor-3', status: 'completed', decision: 'approved', feedback: 'Outstanding canvas setup! The animation loop is perfectly implemented. The ResizeObserver + devicePixelRatio handling is exactly right — this is how professionals do it. Excellent work!', strengths: ['Perfect animation loop with proper cleanup', 'Retina/HiDPI support', 'Responsive canvas sizing', 'Clean teardown on unmount'], improvements: ['Add FPS counter for debugging in development mode'], grade: 98, rubricScores: [{ category: 'Technical Correctness', weight: 35, score: 5, maxScore: 5 }, { category: 'Performance', weight: 30, score: 5, maxScore: 5 }, { category: 'Code Quality', weight: 20, score: 5, maxScore: 5 }, { category: 'Best Practices', weight: 15, score: 5, maxScore: 5 }], slaDeadline: '2024-03-10T13:00:00Z', completedAt: '2024-03-09T10:00:00Z', createdAt: '2024-03-08T15:00:00Z', updatedAt: '2024-03-09T10:00:00Z' },
  { id: 'rev-9', submissionId: 'sub-12', projectId: 'proj-7', deliverableId: 'del-17', reviewerId: 'mentor-5', status: 'completed', decision: 'approved', feedback: 'Great user research! The interviews are thorough and insights are well-synthesised. Your personas feel like real people. The competitive analysis was a great addition.', strengths: ['Thorough interview process', 'Clear and empathetic user personas', 'Insightful journey maps', 'Competitive analysis included'], improvements: ['Include more quantitative data to back up qualitative findings', 'Consider more diverse user segments for the next round'], grade: 90, rubricScores: [{ category: 'Research Quality', weight: 35, score: 5, maxScore: 5 }, { category: 'Synthesis', weight: 30, score: 4, maxScore: 5 }, { category: 'Documentation', weight: 20, score: 5, maxScore: 5 }, { category: 'Insights', weight: 15, score: 4, maxScore: 5 }], slaDeadline: '2024-03-14T16:00:00Z', completedAt: '2024-03-14T11:00:00Z', createdAt: '2024-03-13T10:00:00Z', updatedAt: '2024-03-14T11:00:00Z' },
  { id: 'rev-10', submissionId: 'sub-14', projectId: 'proj-8', deliverableId: 'del-20', reviewerId: 'mentor-4', status: 'completed', decision: 'approved', feedback: 'Excellent Docker setup! Multi-stage builds are well-implemented, cutting image size by 65%. Health checks are a production-readiness win. Very solid foundation for the pipeline.', strengths: ['Multi-stage build optimisation (65% size reduction)', 'Health checks on all services', 'Proper secret management with env files', 'Clean volume configuration'], improvements: ['Add Docker Swarm or Compose deploy config for staging'], grade: 93, rubricScores: [{ category: 'Technical Correctness', weight: 35, score: 5, maxScore: 5 }, { category: 'Optimisation', weight: 25, score: 5, maxScore: 5 }, { category: 'Best Practices', weight: 25, score: 4, maxScore: 5 }, { category: 'Documentation', weight: 15, score: 5, maxScore: 5 }], slaDeadline: '2024-03-17T14:00:00Z', completedAt: '2024-03-16T10:00:00Z', createdAt: '2024-03-15T16:00:00Z', updatedAt: '2024-03-16T10:00:00Z' },
  { id: 'rev-11', submissionId: 'sub-16', projectId: 'proj-9', reviewerId: 'mentor-5', status: 'completed', decision: 'approved', feedback: 'Beautiful portfolio design! The dark theme is well-executed and the variable font usage is sophisticated. The project card hierarchy is clear. Really excited to see this built.', strengths: ['Stunning visual design', 'Smart use of variable fonts', 'Responsive layouts well thought out', 'Clear information hierarchy'], improvements: ['Add micro-interactions to project cards', 'Consider a subtle noise texture on the hero background'], grade: 95, rubricScores: [{ category: 'Visual Design', weight: 35, score: 5, maxScore: 5 }, { category: 'UX', weight: 30, score: 5, maxScore: 5 }, { category: 'Responsiveness', weight: 20, score: 5, maxScore: 5 }, { category: 'Polish', weight: 15, score: 4, maxScore: 5 }], slaDeadline: '2024-04-12T16:00:00Z', completedAt: '2024-04-12T09:00:00Z', createdAt: '2024-04-11T10:00:00Z', updatedAt: '2024-04-12T09:00:00Z' },
  { id: 'rev-12', submissionId: 'sub-17', projectId: 'proj-10', reviewerId: 'mentor-6', status: 'completed', decision: 'approved', feedback: 'Well-planned capstone project! The scope is appropriate and tech stack choices are well-justified. The risk register shows maturity. The roadmap is realistic.', strengths: ['Clear project scope', 'Well-justified tech choices', 'Realistic roadmap with milestones', 'Risk register included'], improvements: ['Add more detailed user stories with acceptance criteria', 'Define measurable success metrics'], grade: 92, rubricScores: [{ category: 'Planning', weight: 35, score: 5, maxScore: 5 }, { category: 'Technical Design', weight: 30, score: 4, maxScore: 5 }, { category: 'Documentation', weight: 20, score: 5, maxScore: 5 }, { category: 'Scope Definition', weight: 15, score: 5, maxScore: 5 }], slaDeadline: '2024-04-17T17:00:00Z', completedAt: '2024-04-17T10:00:00Z', createdAt: '2024-04-16T09:00:00Z', updatedAt: '2024-04-17T10:00:00Z' },
  { id: 'rev-13', submissionId: 'sub-18', projectId: 'proj-10', reviewerId: 'mentor-6', status: 'completed', decision: 'approved', feedback: 'Outstanding capstone delivery! The demo video is confident and clear. The live deployment is stable. The written case study is exactly what employers want to see. Portfolio-ready work.', strengths: ['Polished demo video', 'Stable live deployment', 'Thorough written case study', 'Confident presentation to cohort'], improvements: ['Consider adding a blog post about the architecture decisions'], grade: 97, rubricScores: [{ category: 'Delivery Quality', weight: 35, score: 5, maxScore: 5 }, { category: 'Technical Achievement', weight: 30, score: 5, maxScore: 5 }, { category: 'Communication', weight: 20, score: 5, maxScore: 5 }, { category: 'Documentation', weight: 15, score: 5, maxScore: 5 }], slaDeadline: '2024-06-01T17:00:00Z', completedAt: '2024-05-31T09:00:00Z', createdAt: '2024-05-30T19:00:00Z', updatedAt: '2024-05-31T09:00:00Z' },
  // Pending reviews (in queue)
  { id: 'rev-14', submissionId: 'sub-3', projectId: 'proj-1', deliverableId: 'del-3', reviewerId: 'mentor-1', status: 'pending', feedback: '', slaDeadline: '2024-02-21T13:00:00Z', createdAt: '2024-02-19T13:00:00Z', updatedAt: '2024-02-19T13:00:00Z' },
  { id: 'rev-15', submissionId: 'sub-6', projectId: 'proj-2', deliverableId: 'del-8', reviewerId: 'mentor-1', status: 'pending', feedback: '', slaDeadline: '2024-03-19T15:00:00Z', createdAt: '2024-03-17T15:00:00Z', updatedAt: '2024-03-17T15:00:00Z' },
  { id: 'rev-16', submissionId: 'sub-11', projectId: 'proj-5', deliverableId: 'del-15', reviewerId: 'mentor-3', status: 'in-progress', feedback: '', slaDeadline: '2024-03-19T14:00:00Z', startedAt: '2024-03-18T09:00:00Z', createdAt: '2024-03-17T14:00:00Z', updatedAt: '2024-03-18T09:00:00Z' },
  { id: 'rev-17', submissionId: 'sub-13', projectId: 'proj-7', deliverableId: 'del-18', reviewerId: 'mentor-5', status: 'pending', feedback: '', slaDeadline: '2024-03-21T15:00:00Z', createdAt: '2024-03-19T15:00:00Z', updatedAt: '2024-03-19T15:00:00Z' },
  { id: 'rev-18', submissionId: 'sub-15', projectId: 'proj-8', deliverableId: 'del-21', reviewerId: 'mentor-4', status: 'in-progress', feedback: '', slaDeadline: '2024-03-26T15:00:00Z', startedAt: '2024-03-25T10:00:00Z', createdAt: '2024-03-24T15:00:00Z', updatedAt: '2024-03-25T10:00:00Z' },
]

// Portfolio Projects
export const mockPortfolioProjects: PortfolioProject[] = [
  { id: 'port-1', studentId: 'student-1', submissionId: 'sub-2', title: 'Reusable Component Library', description: 'A comprehensive React component library built with TypeScript, featuring accessible components with multiple variants and states.', thumbnailUrl: 'https://images.unsplash.com/photo-1618477388954-7852f32655ec?w=800&h=600&fit=crop', tags: ['React', 'TypeScript', 'Storybook', 'Accessibility'], featured: true, createdAt: '2024-02-17T10:00:00Z' },
  { id: 'port-2', studentId: 'student-2', submissionId: 'sub-5', title: 'Next.js Admin Dashboard', description: 'Full-featured admin dashboard with authentication, data visualisation, and real-time updates.', thumbnailUrl: 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=800&h=600&fit=crop', tags: ['Next.js', 'Authentication', 'Charts', 'TypeScript'], featured: true, createdAt: '2024-03-15T10:00:00Z' },
  { id: 'port-3', studentId: 'student-3', submissionId: 'sub-8', title: 'RESTful API', description: 'Scalable REST API built with Express.js and TypeScript, featuring JWT authentication and comprehensive error handling.', thumbnailUrl: 'https://images.unsplash.com/photo-1558494949-ef010cbdcc31?w=800&h=600&fit=crop', tags: ['Node.js', 'Express', 'API Design', 'PostgreSQL'], featured: false, createdAt: '2024-02-22T10:00:00Z' },
  { id: 'port-4', studentId: 'student-5', submissionId: 'sub-10', title: 'Generative Art System', description: 'Interactive particle system creating beautiful generative art with mouse interaction and physics simulation.', thumbnailUrl: 'https://images.unsplash.com/photo-1557672172-298e090bd0f1?w=800&h=600&fit=crop', tags: ['Canvas API', 'Creative Coding', 'Algorithms', 'Animation'], featured: true, createdAt: '2024-03-10T10:00:00Z' },
]

// Activities
export const mockActivities: Activity[] = [
  { id: 'act-1', userId: 'student-1', type: 'submission', entityId: 'sub-3', entityType: 'submission', description: 'Submitted Input Component for review', createdAt: '2024-02-19T13:00:00Z' },
  { id: 'act-2', userId: 'mentor-1', type: 'review', entityId: 'rev-2', entityType: 'review', description: 'Approved Button Component submission', createdAt: '2024-02-16T11:00:00Z' },
  { id: 'act-3', userId: 'student-2', type: 'submission', entityId: 'sub-6', entityType: 'submission', description: 'Submitted Dashboard Layout for review', createdAt: '2024-03-17T15:00:00Z' },
  { id: 'act-4', userId: 'student-9', type: 'task', entityId: 'task-30', entityType: 'task', description: 'Started working on Build Portfolio Site', createdAt: '2024-04-20T14:00:00Z' },
  { id: 'act-5', userId: 'mentor-3', type: 'review', entityId: 'rev-4', entityType: 'review', description: 'Requested changes on Authentication submission', createdAt: '2024-03-14T10:00:00Z' },
]

// Notifications
export const mockNotifications: Notification[] = [
  { id: 'notif-1', userId: 'student-1', type: 'success', title: 'Submission Approved', message: 'Your Button Component has been approved by Alex Rivera.', read: false, actionUrl: '/submissions/sub-2', createdAt: '2024-02-16T11:00:00Z' },
  { id: 'notif-2', userId: 'student-2', type: 'warning', title: 'Changes Requested', message: 'Morgan Lee has requested changes on your Authentication submission.', read: false, actionUrl: '/submissions/sub-5', createdAt: '2024-03-14T10:00:00Z' },
  { id: 'notif-3', userId: 'student-2', type: 'warning', title: 'Deadline Approaching', message: 'Dashboard Layout task is due in 2 days.', read: false, actionUrl: '/tasks/task-8', createdAt: '2024-03-16T09:00:00Z' },
  { id: 'notif-4', userId: 'mentor-1', type: 'info', title: 'New Submission', message: 'Emma Thompson submitted Input Component for review.', read: true, actionUrl: '/review-studio', createdAt: '2024-02-19T13:00:00Z' },
  { id: 'notif-5', userId: 'mentor-1', type: 'info', title: 'New Submission', message: 'Liam Martinez submitted Dashboard Layout for review.', read: false, actionUrl: '/review-studio', createdAt: '2024-03-17T15:00:00Z' },
]

// Career Resources
export const mockCareerResources: CareerResource[] = [
  { id: 'career-1', title: 'How to Write a Developer Resume That Stands Out', description: 'Key elements of a strong developer resume — from showcasing projects to highlighting technical skills.', type: 'article', url: 'https://example.com/resume-tips', tags: ['resume', 'career', 'job-search'], featured: true, createdAt: '2024-01-15T10:00:00Z' },
  { id: 'career-2', title: 'Top 50 Frontend Interview Questions', description: 'Common frontend interview questions with detailed answers and explanations.', type: 'article', url: 'https://example.com/interview-questions', tags: ['interview', 'frontend', 'preparation'], featured: true, createdAt: '2024-01-20T10:00:00Z' },
  { id: 'career-3', title: 'Building Your Developer Portfolio', description: 'Step-by-step guide to creating a portfolio that impresses recruiters.', type: 'video', url: 'https://example.com/portfolio-guide', tags: ['portfolio', 'career', 'personal-branding'], featured: false, createdAt: '2024-02-01T10:00:00Z' },
  { id: 'career-4', title: 'Negotiating Your First Tech Job Offer', description: 'Tips and strategies for negotiating salary and benefits as a junior developer.', type: 'article', url: 'https://example.com/salary-negotiation', tags: ['negotiation', 'salary', 'career'], featured: false, createdAt: '2024-02-10T10:00:00Z' },
]

// Job Postings
export const mockJobPostings: JobPosting[] = [
  { id: 'job-1', company: 'TechCorp', position: 'Junior Frontend Developer', location: 'San Francisco, CA', type: 'full-time', description: 'Join our team to build modern web applications using React and TypeScript.', requirements: ['Strong JavaScript fundamentals', 'Experience with React', 'Understanding of HTML/CSS', 'Portfolio of projects'], applyUrl: 'https://techcorp.com/careers/junior-frontend', postedAt: '2024-03-15T10:00:00Z' },
  { id: 'job-2', company: 'StartupXYZ', position: 'Full Stack Engineer Intern', location: 'Remote', type: 'internship', description: '3-month internship building features for our SaaS platform using Next.js and Node.js.', requirements: ['Familiarity with React or Vue', 'Basic backend experience', 'Git proficiency', 'Eager to learn'], applyUrl: 'https://startupxyz.com/internship', postedAt: '2024-03-20T10:00:00Z' },
  { id: 'job-3', company: 'Design Studio', position: 'Creative Developer', location: 'New York, NY', type: 'full-time', description: 'Create interactive web experiences combining design and code.', requirements: ['Strong JavaScript skills', 'Experience with Canvas/WebGL', 'Eye for design', 'Portfolio of creative work'], applyUrl: 'https://designstudio.com/jobs/creative-dev', postedAt: '2024-03-18T10:00:00Z' },
]
