import type { Workstream } from './types'

export const allWorkstreams: Workstream[] = [
  // ─────────────────────────────────────────────────────────────
  // 1. DIGITAL MARKETING
  // ─────────────────────────────────────────────────────────────
  {
    id: 'ws-dm',
    name: 'Digital Marketing',
    shortName: 'Marketing',
    description: 'Master performance marketing, content systems, paid ads, and growth strategy. Build real campaigns for real brands.',
    tagline: 'From zero to campaign-ready in 12 weeks.',
    icon: 'TrendingUp',
    color: 'text-orange-400',
    accentColor: 'orange',
    order: 1,
    cohortIds: ['cohort-1', 'cohort-2', 'cohort-3'],
    projectIds: [],
    totalEstimatedWeeks: 12,
    internshipWeight: 100,
    tools: [
      { name: 'Meta Ads Manager', category: 'Paid Ads', description: 'Campaign creation, A/B testing, audience targeting', required: true },
      { name: 'Google Ads', category: 'Paid Ads', description: 'Search, Display, and Performance Max campaigns', required: true },
      { name: 'Canva Pro', category: 'Creative', description: 'Ad creative, social graphics, presentations', required: true },
      { name: 'CapCut / Adobe Express', category: 'Video', description: 'Short-form video editing for social content', required: true },
      { name: 'Google Analytics 4', category: 'Analytics', description: 'Event tracking, conversion goals, attribution', required: true },
      { name: 'Semrush / Ahrefs', category: 'SEO', description: 'Keyword research, backlink audits, competitor analysis', required: false },
      { name: 'Notion', category: 'Operations', description: 'Content calendar, client SOPs, reporting templates', required: true },
      { name: 'Webflow / Framer', category: 'Landing Pages', description: 'No-code landing page builds', required: false },
      { name: 'Hotjar', category: 'CRO', description: 'Heatmaps, session recordings, funnel analysis', required: false },
    ],
    syllabus: [
      {
        level: 'Foundation',
        description: 'Build your understanding of brand, content, and digital channels. Leave with a functioning content system and your first creative assets.',
        workPackages: [
          {
            id: 'dm-f-1',
            title: 'Brand & Market Basics',
            goal: 'Understand brand positioning, target audience segmentation, and competitive landscape analysis.',
            skills: ['Brand positioning', 'Audience segmentation', 'Competitor research', 'Value proposition writing'],
            tools: ['Notion', 'Google Trends', 'Semrush (free tier)'],
            practiceTasks: [
              'Pick 2 brands in the same niche and map their positioning',
              'Define 3 audience personas with pain points and buying triggers',
              'Write a positioning statement using the PAS framework',
            ],
            finalDeliverable: 'Brand Strategy One-Pager: positioning, target personas, unique value proposition, and competitive differentiation.',
            estimatedTime: '1 week',
          },
          {
            id: 'dm-f-2',
            title: 'Content System (30-Day Engine)',
            goal: 'Design and launch a repeatable 30-day content system that runs without burnout.',
            skills: ['Content calendar planning', 'Batch content creation', 'Hook writing', 'Platform-specific formatting'],
            tools: ['Notion', 'Canva Pro', 'ChatGPT for ideation'],
            practiceTasks: [
              'Write 10 hooks for 3 different formats (Reel, Carousel, Story)',
              'Build a 30-day content calendar with themes and post types',
              'Create 5 posts for one platform using the calendar',
            ],
            finalDeliverable: '30-day content calendar with 15 produced posts (5 Reels scripts, 5 Carousels, 5 captions) and a batch workflow doc.',
            estimatedTime: '2 weeks',
          },
          {
            id: 'dm-f-3',
            title: 'Social Media Operations',
            goal: 'Operate a brand social media presence efficiently across 2 platforms.',
            skills: ['Platform algorithms', 'Community management', 'Analytics interpretation', 'Posting cadence'],
            tools: ['Meta Business Suite', 'Buffer / Later', 'GA4'],
            practiceTasks: [
              'Audit an existing brand account and identify 3 quick wins',
              'Respond to 10 simulated comments in the brand voice',
              'Pull weekly analytics and write a 1-paragraph performance summary',
            ],
            finalDeliverable: 'Social Media Playbook: platform guidelines, brand voice rules, post templates, and a 2-week performance report.',
            estimatedTime: '1 week',
          },
          {
            id: 'dm-f-4',
            title: 'Creatives that Convert',
            goal: 'Design ad and organic creatives using conversion psychology principles.',
            skills: ['Copywriting frameworks', 'Ad creative principles', 'CTA design', 'Visual hierarchy'],
            tools: ['Canva Pro', 'CapCut', 'Adobe Express'],
            practiceTasks: [
              'Rewrite 3 weak CTAs to be specific and outcome-driven',
              'Design a before/after ad creative for a product',
              'Create a 15-second Reel script using the AIDA framework',
            ],
            finalDeliverable: 'Ad Creative Library: 6 static ad creatives + 2 Reel scripts across 2 product categories, with copywriting rationale doc.',
            estimatedTime: '2 weeks',
          },
        ],
      },
      {
        level: 'Intermediate',
        description: 'Run real paid ad campaigns, build high-converting landing pages, and report performance like an agency.',
        workPackages: [
          {
            id: 'dm-i-1',
            title: 'Paid Ads Fundamentals',
            goal: 'Launch and optimise Meta and Google ad campaigns within a test budget.',
            skills: ['Campaign structure (Campaign > Ad Set > Ad)', 'Audience targeting', 'Bid strategies', 'A/B testing'],
            tools: ['Meta Ads Manager', 'Google Ads', 'Canva Pro'],
            practiceTasks: [
              'Build a cold/warm/hot funnel audience structure for a fashion brand',
              'Set up a split test between 2 ad creatives with identical targeting',
              'Calculate ROAS, CPM, CTR, and CPC from a mock results table',
            ],
            finalDeliverable: 'Campaign Case Study: strategy doc, targeting rationale, creative variations, budget plan, and 2-week performance analysis.',
            estimatedTime: '2 weeks',
          },
          {
            id: 'dm-i-2',
            title: 'Landing Pages & Conversion',
            goal: 'Design and build landing pages optimised for conversion using CRO principles.',
            skills: ['Landing page anatomy', 'CRO principles', 'Headline writing', 'Form optimisation'],
            tools: ['Webflow / Framer', 'Hotjar', 'Google Optimize'],
            practiceTasks: [
              'Identify 5 conversion killers on an existing landing page',
              'Write 3 headline variants using benefit-led copywriting',
              'Build a 1-section landing page hero in Framer',
            ],
            finalDeliverable: 'Landing Page Wireframe + Live Build: above-fold, social proof, CTA, and FAQ sections, with CRO rationale document.',
            estimatedTime: '2 weeks',
          },
          {
            id: 'dm-i-3',
            title: 'SEO + Local Growth',
            goal: 'Apply technical and on-page SEO to grow organic search traffic for a local or niche brand.',
            skills: ['Keyword research', 'On-page SEO', 'Google Business Profile', 'Content briefs'],
            tools: ['Semrush', 'Ahrefs', 'Google Search Console', 'Screaming Frog (free)'],
            practiceTasks: [
              'Run a keyword gap analysis for a brand vs. 2 competitors',
              'Write a fully optimised blog post brief (1,500 words)',
              'Audit a Google Business Profile and identify 5 improvement areas',
            ],
            finalDeliverable: 'SEO Growth Plan: keyword targets, on-page audit, content brief, and GBP optimisation report.',
            estimatedTime: '1 week',
          },
          {
            id: 'dm-i-4',
            title: 'Analytics & Reporting',
            goal: 'Build GA4 tracking infrastructure and deliver a professional performance report.',
            skills: ['GA4 event setup', 'Conversion tracking', 'UTM parameters', 'Data storytelling'],
            tools: ['Google Analytics 4', 'Google Tag Manager', 'Looker Studio'],
            practiceTasks: [
              'Set up 4 custom GA4 events for an e-commerce funnel',
              'Build a UTM tracking sheet for a multi-channel campaign',
              'Create a Looker Studio dashboard with 5 key metrics',
            ],
            finalDeliverable: 'Reporting Dashboard: Looker Studio report with channel performance, conversion funnel, and actionable insights section.',
            estimatedTime: '1 week',
          },
        ],
      },
      {
        level: 'Advanced',
        description: 'Think like a growth strategist. Run sprint-based experiments, build a creative testing lab, and operate with agency-grade SOPs.',
        workPackages: [
          {
            id: 'dm-a-1',
            title: 'Growth Strategy Sprint',
            goal: 'Design a 90-day growth strategy using the AARRR framework for an assigned brand scenario.',
            skills: ['AARRR funnel thinking', 'Experiment design', 'CAC and LTV modelling', 'Channel prioritisation'],
            tools: ['Notion', 'Google Sheets', 'Looker Studio'],
            practiceTasks: [
              'Map the AARRR funnel for 2 SaaS brands with leakage points identified',
              'Design 3 growth experiments with hypothesis, metric, and success criteria',
              'Model CAC vs LTV for 3 marketing channels',
            ],
            finalDeliverable: '90-Day Growth Strategy: AARRR audit, channel mix, experiment backlog, budget model, and KPI dashboard.',
            estimatedTime: '3 weeks',
          },
          {
            id: 'dm-a-2',
            title: 'Performance Creative Lab',
            goal: 'Build a systematic creative testing operation that generates learnings, not just content.',
            skills: ['Creative testing frameworks', 'Winning element isolation', 'UGC direction', 'Script-to-production'],
            tools: ['Meta Ads Manager', 'CapCut', 'Notion Creative OS'],
            practiceTasks: [
              'Build a creative scorecard to rank ad performance by hook/body/CTA',
              'Direct a 30-second UGC-style testimonial video script',
              'Produce a 6-variant creative test matrix for one product',
            ],
            finalDeliverable: 'Performance Creative Report: 6-variant test results, winning element breakdown, iteration recommendations, and creative scoring framework.',
            estimatedTime: '2 weeks',
          },
          {
            id: 'dm-a-3',
            title: 'Agency Workflow & Client SOP',
            goal: 'Build the operational infrastructure to run paid marketing for a client at agency standard.',
            skills: ['Client onboarding', 'SOP documentation', 'Reporting cadence', 'Escalation handling'],
            tools: ['Notion', 'Slack (simulation)', 'Loom'],
            practiceTasks: [
              'Write a client onboarding checklist (access, brand assets, goals)',
              'Build a weekly reporting SOP with sample email templates',
              'Create a campaign escalation decision tree',
            ],
            finalDeliverable: 'Agency Client SOP Kit: onboarding checklist, reporting template, communication protocol, and campaign health dashboard.',
            estimatedTime: '1 week',
          },
        ],
      },
    ],
    rubric: {
      passMark: 70,
      distincionMark: 85,
      categories: [
        { name: 'Strategy & Thinking', weight: 25, criteria: ['Clear audience targeting', 'Logical campaign structure', 'Channel rationale supported by data'] },
        { name: 'Creative Execution', weight: 25, criteria: ['Hook quality and originality', 'On-brand visuals', 'CTA clarity and placement'] },
        { name: 'Analytics & Measurement', weight: 20, criteria: ['Correct metric selection', 'Accurate interpretation', 'Actionable recommendations'] },
        { name: 'Written Communication', weight: 20, criteria: ['Clear and concise copy', 'Correct grammar and tone', 'Appropriate platform formatting'] },
        { name: 'Process & Documentation', weight: 10, criteria: ['Organised deliverables', 'SOP/workflow quality', 'Naming conventions followed'] },
      ],
    },
    portfolioOutputs: [
      { id: 'dm-po-1', title: 'Campaign Case Study', description: 'Full paid campaign from strategy to results, documented as an investor-grade case study.', level: 'Intermediate', format: 'PDF or Notion page' },
      { id: 'dm-po-2', title: 'Ad Creative Library', description: 'Branded collection of 12+ static and video ad creatives with performance notes.', level: 'Foundation', format: 'Canva shared folder + PDF' },
      { id: 'dm-po-3', title: 'Landing Page Wireframe', description: 'CRO-optimised wireframe with copywriting rationale and live Framer/Webflow build.', level: 'Intermediate', format: 'Framer URL + Figma file' },
      { id: 'dm-po-4', title: 'Reporting Dashboard', description: 'Live Looker Studio dashboard tracking campaign performance across all channels.', level: 'Intermediate', format: 'Looker Studio live link' },
    ],
  },

  // ─────────────────────────────────────────────────────────────
  // 2. SOFTWARE & WEB DEVELOPMENT
  // ─────────────────────────────────────────────────────────────
  {
    id: 'ws-swd',
    name: 'Software & Web Development',
    shortName: 'Development',
    description: 'Build investor-grade web apps with React, Next.js, and AI integrations. From Git basics to production-ready deployments.',
    tagline: 'Ship real products. Learn by building.',
    icon: 'Code2',
    color: 'text-blue-400',
    accentColor: 'blue',
    order: 2,
    cohortIds: ['cohort-1', 'cohort-2', 'cohort-3'],
    projectIds: ['proj-1', 'proj-2'],
    totalEstimatedWeeks: 14,
    internshipWeight: 100,
    tools: [
      { name: 'VS Code', category: 'IDE', description: 'Primary development environment with extensions', required: true },
      { name: 'Git + GitHub', category: 'Version Control', description: 'Branching, PRs, code review workflow', required: true },
      { name: 'Next.js', category: 'Framework', description: 'App Router, Server Components, API routes', required: true },
      { name: 'Tailwind CSS', category: 'Styling', description: 'Utility-first CSS with shadcn/ui', required: true },
      { name: 'TypeScript', category: 'Language', description: 'Type safety, interfaces, generics', required: true },
      { name: 'Vercel', category: 'Deployment', description: 'CI/CD, preview deployments, environment variables', required: true },
      { name: 'Supabase', category: 'Backend', description: 'Auth, database, row-level security', required: false },
      { name: 'Cursor / GitHub Copilot', category: 'AI Tools', description: 'AI-assisted development workflow', required: false },
      { name: 'Figma', category: 'Design', description: 'Reading and implementing design specs', required: false },
    ],
    syllabus: [
      {
        level: 'Foundation',
        description: 'Learn the core building blocks of modern web development. By the end you will have a working React app deployed live.',
        workPackages: [
          {
            id: 'swd-f-1',
            title: 'Web Basics + Git',
            goal: 'Understand HTML, CSS, JavaScript fundamentals and the Git workflow used in professional teams.',
            skills: ['HTML semantics', 'CSS box model', 'JavaScript ES6+', 'Git branching', 'Pull request workflow'],
            tools: ['VS Code', 'Git + GitHub', 'Chrome DevTools'],
            practiceTasks: [
              'Build a personal bio page from scratch with no frameworks',
              'Create a GitHub repo, make 5 commits with meaningful messages',
              'Open a pull request and write a description explaining your changes',
            ],
            finalDeliverable: 'Bio/Portfolio Landing Page: semantic HTML, custom CSS, deployed on GitHub Pages, with a complete Git history of meaningful commits.',
            estimatedTime: '1 week',
          },
          {
            id: 'swd-f-2',
            title: 'UI Building with Tailwind',
            goal: 'Build pixel-perfect, responsive UIs using Tailwind CSS and shadcn/ui components.',
            skills: ['Utility-first CSS', 'Responsive breakpoints', 'Component composition', 'Dark mode'],
            tools: ['Tailwind CSS', 'shadcn/ui', 'VS Code'],
            practiceTasks: [
              'Clone a Dribbble design using only Tailwind (no custom CSS)',
              'Build a responsive navbar that collapses on mobile',
              'Add a dark/light mode toggle to an existing page',
            ],
            finalDeliverable: 'Marketing Landing Page: full-page design built in Tailwind with hero, features section, pricing table, and footer — fully responsive.',
            estimatedTime: '1.5 weeks',
          },
          {
            id: 'swd-f-3',
            title: 'React Fundamentals',
            goal: 'Build interactive UIs with React components, state, and props.',
            skills: ['JSX syntax', 'useState and useEffect', 'Props and component composition', 'Event handling', 'Lists and keys'],
            tools: ['React', 'Vite', 'TypeScript'],
            practiceTasks: [
              'Build a todo list with add, complete, and delete functionality',
              'Create a colour picker component that previews the selected colour',
              'Build a simple countdown timer with start/pause/reset',
            ],
            finalDeliverable: 'Interactive Dashboard Widget: a React app with at least 3 components, live state, and user interactions (search, filter, or sort).',
            estimatedTime: '2 weeks',
          },
          {
            id: 'swd-f-4',
            title: 'Forms & Validation',
            goal: 'Build accessible, validated forms with real-time feedback and error states.',
            skills: ['Controlled inputs', 'Form validation logic', 'Error state UI', 'Accessibility (ARIA)'],
            tools: ['React Hook Form', 'Zod', 'shadcn/ui Form'],
            practiceTasks: [
              'Build a multi-step form with 3 steps and a progress indicator',
              'Add inline validation with Zod schema (email, password strength)',
              'Make the form fully keyboard-navigable',
            ],
            finalDeliverable: 'Registration & Onboarding Form: multi-step, Zod-validated, accessible form with field-level errors and a confirmation step.',
            estimatedTime: '1 week',
          },
        ],
      },
      {
        level: 'Intermediate',
        description: 'Move from components to complete products. Learn the Next.js App Router, authentication, API design, and AI integration patterns.',
        workPackages: [
          {
            id: 'swd-i-1',
            title: 'Next.js App Router',
            goal: 'Build full-stack applications using the Next.js 14+ App Router with Server and Client Components.',
            skills: ['File-based routing', 'Server Components', 'Data fetching patterns', 'Loading and error boundaries', 'Metadata API'],
            tools: ['Next.js', 'TypeScript', 'Vercel'],
            practiceTasks: [
              'Build a blog with dynamic routes using mock JSON data',
              'Add a loading skeleton that appears during data fetches',
              'Deploy to Vercel and set up a custom domain',
            ],
            finalDeliverable: 'Content Platform: Next.js app with dynamic routes, SSR data fetching, loading states, error boundaries, and live Vercel deployment.',
            estimatedTime: '2 weeks',
          },
          {
            id: 'swd-i-2',
            title: 'Role-Based Access Control (Frontend)',
            goal: 'Implement role-based navigation, route guards, and permission-aware UI patterns.',
            skills: ['Auth context patterns', 'Route protection', 'Conditional rendering by role', 'Session management'],
            tools: ['Next.js', 'Supabase Auth / NextAuth', 'React Context'],
            practiceTasks: [
              'Build a role switcher that changes the visible sidebar items',
              'Create a protected route that redirects unauthenticated users',
              'Hide/show action buttons based on the current user role',
            ],
            finalDeliverable: 'RBAC Navigation System: multi-role app (admin/user/guest) with protected routes, role-aware menus, and session persistence.',
            estimatedTime: '2 weeks',
          },
          {
            id: 'swd-i-3',
            title: 'API Design (Mock)',
            goal: 'Design and mock RESTful APIs that a frontend can integrate against before the backend is ready.',
            skills: ['REST principles', 'API route handlers', 'Request/response shapes', 'Error handling conventions'],
            tools: ['Next.js API Routes', 'Zod', 'Postman'],
            practiceTasks: [
              'Design a REST API spec for a task management app (OpenAPI format)',
              'Build 4 API route handlers with proper HTTP status codes',
              'Add Zod validation to all POST/PATCH endpoints',
            ],
            finalDeliverable: 'Mock API Layer: 8 route handlers with Zod validation, correct status codes, and a Postman collection with test cases.',
            estimatedTime: '1.5 weeks',
          },
          {
            id: 'swd-i-4',
            title: 'AI Integration UI Patterns',
            goal: 'Integrate AI capabilities (streaming text, image generation, semantic search) into a real product UI.',
            skills: ['Vercel AI SDK', 'Streaming responses', 'Tool calls UI', 'Loading states for AI'],
            tools: ['Vercel AI SDK', 'OpenAI / Anthropic', 'Next.js'],
            practiceTasks: [
              'Build a streaming chat interface with typing indicators',
              'Add an AI "suggest improvements" button to a form',
              'Create a semantic search bar that queries an AI model',
            ],
            finalDeliverable: 'AI Assist Interface: a Next.js app feature that uses streaming AI responses with a polished UI (loading states, error handling, retry).',
            estimatedTime: '2 weeks',
          },
        ],
      },
      {
        level: 'Advanced',
        description: 'Architect, collaborate, and deploy like a senior engineer. Build production-grade systems with collaboration features.',
        workPackages: [
          {
            id: 'swd-a-1',
            title: 'Product Architecture',
            goal: 'Design the technical architecture for a multi-feature product, making data, component, and deployment decisions.',
            skills: ['System design thinking', 'Component hierarchy', 'State management strategy', 'Database schema design'],
            tools: ['Excalidraw', 'Notion', 'Next.js', 'Supabase'],
            practiceTasks: [
              'Draw an ERD for a project management tool',
              'Design the component tree for a dashboard with 5 data sources',
              'Write an Architecture Decision Record (ADR) for a tech choice',
            ],
            finalDeliverable: 'Investor-Grade Portal UI: fully architected, multi-role web portal with documented system design, component library, and Supabase schema.',
            estimatedTime: '3 weeks',
          },
          {
            id: 'swd-a-2',
            title: 'Collaboration Systems',
            goal: 'Build systems for comments, activity logs, notifications, and real-time updates across a team product.',
            skills: ['Optimistic updates', 'Activity feed design', 'Notification systems', 'Real-time subscriptions'],
            tools: ['Supabase Realtime', 'Next.js', 'Zustand / Context'],
            practiceTasks: [
              'Build an activity log component that shows timestamped user actions',
              'Implement a comment thread with replies and resolve/unresolve',
              'Add real-time notifications using Supabase Realtime',
            ],
            finalDeliverable: 'Collaboration Module: comment threads, activity log, and notification system with real-time updates, integrated into the portal UI.',
            estimatedTime: '2 weeks',
          },
          {
            id: 'swd-a-3',
            title: 'Deployment Concepts',
            goal: 'Understand and implement CI/CD pipelines, environment variable management, and production deployment best practices.',
            skills: ['CI/CD pipelines', 'Environment variables', 'Preview deployments', 'Error monitoring'],
            tools: ['Vercel', 'GitHub Actions', 'Sentry'],
            practiceTasks: [
              'Set up a GitHub Actions workflow that runs tests on every PR',
              'Configure Sentry error tracking with source maps on Vercel',
              'Write a deployment checklist with 10 production readiness checks',
            ],
            finalDeliverable: 'Production-Ready Deployment: app on Vercel with CI/CD pipeline, error monitoring, preview deployments, and a deployment runbook.',
            estimatedTime: '1 week',
          },
        ],
      },
    ],
    rubric: {
      passMark: 70,
      distincionMark: 85,
      categories: [
        { name: 'Code Quality', weight: 30, criteria: ['Clean, readable code', 'Consistent naming conventions', 'No dead code or console.logs'] },
        { name: 'Functionality', weight: 30, criteria: ['All requirements implemented', 'Edge cases handled', 'Error states present'] },
        { name: 'UI/UX Implementation', weight: 20, criteria: ['Responsive layout', 'Accessible components', 'Loading and empty states'] },
        { name: 'Architecture', weight: 15, criteria: ['Sensible component breakdown', 'State managed correctly', 'No unnecessary re-renders'] },
        { name: 'Documentation', weight: 5, criteria: ['README present', 'Code comments where needed', 'Deployment instructions clear'] },
      ],
    },
    portfolioOutputs: [
      { id: 'swd-po-1', title: 'Investor-Grade Portal UI', description: 'Full-stack multi-role web portal with documented architecture, live on Vercel.', level: 'Advanced', format: 'Live URL + GitHub repo' },
      { id: 'swd-po-2', title: 'Component System', description: 'Reusable Tailwind/shadcn component library with consistent design tokens.', level: 'Foundation', format: 'GitHub repo + Storybook' },
      { id: 'swd-po-3', title: 'RBAC Navigation', description: 'Multi-role application with protected routes and permission-aware UI.', level: 'Intermediate', format: 'Live URL + GitHub repo' },
      { id: 'swd-po-4', title: 'AI Assist Interface', description: 'Streaming AI integration with polished loading states and error handling.', level: 'Intermediate', format: 'Live URL + video walkthrough' },
    ],
  },

  // ─────────────────────────────────────────────────────────────
  // 3. MEDIA PRODUCTION
  // ─────────────────────────────────────────────────────────────
  {
    id: 'ws-mp',
    name: 'Media Production',
    shortName: 'Media',
    description: 'Learn cinematic storytelling, commercial production, and post-production workflows used by leading content studios.',
    tagline: 'Direct. Edit. Deliver. Repeat.',
    icon: 'Film',
    color: 'text-red-400',
    accentColor: 'red',
    order: 3,
    cohortIds: ['cohort-1', 'cohort-2', 'cohort-3'],
    projectIds: ['proj-5', 'proj-6'],
    totalEstimatedWeeks: 12,
    internshipWeight: 100,
    tools: [
      { name: 'Adobe Premiere Pro', category: 'Editing', description: 'Primary non-linear video editor', required: true },
      { name: 'DaVinci Resolve', category: 'Colour Grading', description: 'Professional colour correction and grading', required: true },
      { name: 'Adobe After Effects', category: 'Motion Graphics', description: 'Animation, lower thirds, compositing', required: false },
      { name: 'CapCut', category: 'Social Editing', description: 'Fast edits for short-form social content', required: true },
      { name: 'Audacity / Adobe Audition', category: 'Audio', description: 'Audio cleanup, music layering, SFX', required: true },
      { name: 'Frame.io', category: 'Collaboration', description: 'Client review, time-coded comments', required: false },
      { name: 'Canon / Sony / iPhone', category: 'Camera', description: 'Camera operation, manual settings, stabilisation', required: true },
      { name: 'Aputure / NanLite', category: 'Lighting', description: '3-point lighting, colour temperature', required: false },
    ],
    syllabus: [
      {
        level: 'Foundation',
        description: 'Master the fundamentals of camera, lighting, and editing. Leave with your first complete short-form video.',
        workPackages: [
          {
            id: 'mp-f-1',
            title: 'Camera & Lighting Basics',
            goal: 'Control a camera manually and set up 3-point lighting for an interview or product shot.',
            skills: ['Exposure triangle (ISO, aperture, shutter)', 'White balance', '3-point lighting setup', 'Shot composition rules'],
            tools: ['Canon / Sony / iPhone', 'Aputure / NanLite', 'Reflectors'],
            practiceTasks: [
              'Shoot the same scene in 3 different exposure settings and compare',
              'Set up a 3-point interview lighting configuration',
              'Film 10 different shot types (wide, medium, close-up, OTS, etc.)',
            ],
            finalDeliverable: 'Interview Setup Video: 90-second self-interview or subject interview with correct exposure, 3-point lighting, and varied shot selection.',
            estimatedTime: '1.5 weeks',
          },
          {
            id: 'mp-f-2',
            title: 'Storytelling for Ads',
            goal: 'Apply cinematic storytelling techniques to create compelling 15–30 second ad structures.',
            skills: ['3-act structure for ads', 'Problem/solution narrative', 'Shot list creation', 'Storyboard drawing'],
            tools: ['Notion (pre-production docs)', 'Procreate / paper storyboard'],
            practiceTasks: [
              'Storyboard a 15-second ad for a fictional product',
              'Identify the narrative structure of 5 real TV ads',
              'Write a shot list with camera movement notes for each shot',
            ],
            finalDeliverable: 'Ad Storyboard + Shot List: a fully storyboarded 30-second ad concept with shot-by-shot direction notes and a pre-production pack.',
            estimatedTime: '1 week',
          },
          {
            id: 'mp-f-3',
            title: 'Editing Fundamentals',
            goal: 'Build a complete edit in Premiere Pro from raw footage to export.',
            skills: ['Timeline management', 'Cut types (cut, J-cut, L-cut)', 'Transitions and pacing', 'Export settings for platforms'],
            tools: ['Adobe Premiere Pro', 'CapCut'],
            practiceTasks: [
              'Assemble a rough cut from 20 minutes of raw footage in under 2 hours',
              'Apply J-cuts and L-cuts to a dialogue scene',
              'Export a file optimised for YouTube vs. Instagram Reels',
            ],
            finalDeliverable: 'Edited Short Film (60–90 seconds): raw footage assembled, trimmed, music synced, and exported in correct spec for 2 platforms.',
            estimatedTime: '2 weeks',
          },
          {
            id: 'mp-f-4',
            title: 'Colour Basics',
            goal: 'Apply colour correction and basic grading to make footage look polished and intentional.',
            skills: ['Colour correction vs. grading', 'Lumetri colour tools', 'LUT application', 'Skin tone matching'],
            tools: ['DaVinci Resolve', 'Adobe Premiere Pro Lumetri'],
            practiceTasks: [
              'Correct 5 clips with different white balance issues',
              'Apply a cinematic LUT and adjust for the specific footage',
              'Match colour between 2 clips filmed in different conditions',
            ],
            finalDeliverable: 'Colour-Graded Sequence: a 60-second sequence with consistent grade applied — colour corrected, LUT applied, and skin tones balanced.',
            estimatedTime: '1 week',
          },
        ],
      },
      {
        level: 'Intermediate',
        description: 'Operate in commercial production environments. Create product content, social reels, and motion graphics at a professional standard.',
        workPackages: [
          {
            id: 'mp-i-1',
            title: 'Commercial Workflow',
            goal: 'Run a complete commercial production from brief to delivery using a professional workflow.',
            skills: ['Production timeline', 'Client brief interpretation', 'Crew roles', 'Delivery formats'],
            tools: ['Frame.io', 'Notion (production docs)', 'Adobe Premiere Pro'],
            practiceTasks: [
              'Break down a client brief into a pre-production checklist',
              'Create a call sheet and production schedule',
              'Submit a cut on Frame.io and respond to time-coded feedback',
            ],
            finalDeliverable: 'Commercial Production Pack: pre-production docs (brief, shot list, call sheet) + delivered 30-second commercial with 2 revision rounds.',
            estimatedTime: '2 weeks',
          },
          {
            id: 'mp-i-2',
            title: 'Motion Graphics Basics',
            goal: 'Create lower thirds, animated titles, and branded transitions using After Effects.',
            skills: ['Keyframe animation', 'Lower thirds design', 'Text animation presets', 'Export for Premiere'],
            tools: ['Adobe After Effects', 'Adobe Premiere Pro'],
            practiceTasks: [
              'Animate a name/title lower third in After Effects',
              'Create a 3-second branded intro animation',
              'Build a template that can be re-used across multiple videos',
            ],
            finalDeliverable: 'Motion Graphics Pack: branded lower thirds, animated title sequence, and 2 transitions — packaged as a Premiere Pro Motion Graphics Template.',
            estimatedTime: '2 weeks',
          },
          {
            id: 'mp-i-3',
            title: 'Product Shoot',
            goal: 'Plan and execute a professional product photography and videography session.',
            skills: ['Product lighting setups', 'Macro and close-up techniques', 'Seamless backgrounds', 'Hero shots'],
            tools: ['Camera + lenses', 'Aputure lighting', 'C-stands and grip'],
            practiceTasks: [
              'Shoot a product with 3 different lighting setups and compare',
              'Create a hero shot using the infinity curve / sweep background',
              'Film a 10-second product reveal video with smooth motion',
            ],
            finalDeliverable: 'Product Shoot Portfolio: 10 edited product stills + a 30-second product video with motion and hero shots across 2 colour backgrounds.',
            estimatedTime: '1.5 weeks',
          },
          {
            id: 'mp-i-4',
            title: 'Social Reels System',
            goal: 'Build a repeatable system for producing 9:16 short-form video content at scale.',
            skills: ['Vertical framing', 'Hook engineering', 'Text overlay design', 'Audio syncing', 'Batch editing'],
            tools: ['CapCut', 'Adobe Premiere Pro', 'Canva (graphics)'],
            practiceTasks: [
              'Edit 3 Reels in 2 hours using a batch editing workflow',
              'Test 3 different hook styles (text hook, visual hook, audio hook)',
              'Build a Reel template in CapCut that can be re-used with new footage',
            ],
            finalDeliverable: 'Reel System: 5 finished Reels (15–30s each) using the batch workflow, with a template file and production time log.',
            estimatedTime: '1 week',
          },
        ],
      },
      {
        level: 'Advanced',
        description: 'Direct and deliver cinematic brand work. Operate sound at studio level and run a production team.',
        workPackages: [
          {
            id: 'mp-a-1',
            title: 'Cinematic Brand Film',
            goal: 'Direct and produce a 2–3 minute brand film that communicates a brand story with high production value.',
            skills: ['Director vision', 'Cinematography (shallow DOF, movement)', 'Voice-over scripting', 'Advanced colour grade'],
            tools: ['Cinema-grade camera', 'DaVinci Resolve', 'Adobe Premiere Pro'],
            practiceTasks: [
              'Write a 2-minute director treatment for a brand film concept',
              'Film a cinematic b-roll sequence with deliberate movement',
              'Grade a 3-minute sequence to achieve a specific visual mood',
            ],
            finalDeliverable: 'Brand Film (2–3 minutes): fully directed, shot, edited, and graded brand story film ready for client delivery.',
            estimatedTime: '3 weeks',
          },
          {
            id: 'mp-a-2',
            title: 'Sound Design & Mix',
            goal: 'Apply professional audio techniques including dialogue cleanup, music layering, and SFX to a complete project.',
            skills: ['Dialogue cleanup', 'Noise reduction', 'Music layering', 'SFX sourcing', 'Final mix levels'],
            tools: ['Adobe Audition', 'Audacity', 'Splice (SFX)'],
            practiceTasks: [
              'Clean up a noisy dialogue recording with noise reduction',
              'Layer 3 audio tracks (music, dialogue, SFX) and balance levels',
              'Mix a 60-second video to broadcast loudness standards (-14 LUFS)',
            ],
            finalDeliverable: 'Mixed Brand Film: the brand film with a full sound mix — cleaned dialogue, music bed, SFX, and exported to broadcast loudness standards.',
            estimatedTime: '1 week',
          },
          {
            id: 'mp-a-3',
            title: 'Studio Team Operations',
            goal: 'Lead a small production team through a full project cycle with proper pre-production, production, and post-production documentation.',
            skills: ['Team briefing', 'Role delegation', 'Production management', 'Client communication'],
            tools: ['Frame.io', 'Notion', 'Slack'],
            practiceTasks: [
              'Create a production bible for a 3-person shoot day',
              'Brief a camera operator using only a visual reference deck',
              'Manage 2 rounds of client revisions using Frame.io',
            ],
            finalDeliverable: 'Studio Operations Pack: production bible, team brief, call sheet, Frame.io review link, and final delivery confirmation.',
            estimatedTime: '2 weeks',
          },
        ],
      },
    ],
    rubric: {
      passMark: 70,
      distincionMark: 85,
      categories: [
        { name: 'Technical Execution', weight: 30, criteria: ['Correct exposure and focus', 'Stable, intentional camera movement', 'Properly exported files'] },
        { name: 'Storytelling & Narrative', weight: 25, criteria: ['Clear narrative structure', 'Emotional impact', 'Pacing appropriate to the format'] },
        { name: 'Post-Production Quality', weight: 25, criteria: ['Colour consistency', 'Audio clarity and balance', 'Smooth edit rhythm'] },
        { name: 'Creative Direction', weight: 15, criteria: ['Unique visual identity', 'Intentional shot selection', 'Brand alignment'] },
        { name: 'Deliverable Completeness', weight: 5, criteria: ['Correct file formats', 'All deliverables submitted', 'Naming conventions followed'] },
      ],
    },
    portfolioOutputs: [
      { id: 'mp-po-1', title: 'Brand Film', description: '2–3 minute cinematic brand film, fully graded and mixed, ready for client use.', level: 'Advanced', format: 'Vimeo link + ProRes master file' },
      { id: 'mp-po-2', title: 'Product Commercial', description: '30-second product commercial with motion, lighting, and professional colour grade.', level: 'Intermediate', format: 'MP4 (H.264) + Vimeo link' },
      { id: 'mp-po-3', title: 'Reel System', description: '5-Reel batch-produced content series with workflow documentation.', level: 'Intermediate', format: 'MP4 files + CapCut template' },
      { id: 'mp-po-4', title: 'Motion Graphics Pack', description: 'Branded lower thirds, title animation, and transitions as MOGRT templates.', level: 'Intermediate', format: 'MOGRT files + Premiere project' },
    ],
  },

  // ─────────────────────────────────────────────────────────────
  // 4. DATA SCIENCE & AI
  // ─────────────────────────────────────────────────────────────
  {
    id: 'ws-ds',
    name: 'Data Science & AI',
    shortName: 'Data & AI',
    description: 'Analyse real datasets, build dashboards, design scoring models, and apply AI tooling to business decisions.',
    tagline: 'Turn data into decisions. Apply AI to real problems.',
    icon: 'BarChart3',
    color: 'text-violet-400',
    accentColor: 'violet',
    order: 4,
    cohortIds: ['cohort-1', 'cohort-2', 'cohort-3'],
    projectIds: [],
    totalEstimatedWeeks: 10,
    internshipWeight: 100,
    tools: [
      { name: 'Python (Pandas, NumPy)', category: 'Analysis', description: 'Data manipulation, statistical analysis', required: true },
      { name: 'Jupyter Notebooks', category: 'Analysis', description: 'Interactive analysis environment', required: true },
      { name: 'Matplotlib / Seaborn', category: 'Visualisation', description: 'Charts, heatmaps, distribution plots', required: true },
      { name: 'Looker Studio / Tableau Public', category: 'Dashboards', description: 'Interactive business dashboards', required: true },
      { name: 'scikit-learn', category: 'ML', description: 'Classification, regression, clustering', required: false },
      { name: 'OpenAI API / LangChain', category: 'AI', description: 'LLM integration, prompt engineering', required: false },
      { name: 'Google Sheets', category: 'Data Entry', description: 'Quick data cleaning and pivot tables', required: true },
      { name: 'Notion', category: 'Documentation', description: 'Insight reports, PRD writing', required: true },
    ],
    syllabus: [
      {
        level: 'Foundation',
        description: 'Build your data fundamentals: clean datasets, create visualisations, and communicate insights clearly.',
        workPackages: [
          {
            id: 'ds-f-1',
            title: 'Data Basics',
            goal: 'Understand data types, cleaning techniques, and how to prepare a dataset for analysis.',
            skills: ['Data types and structures', 'Missing value handling', 'Data cleaning with Pandas', 'Descriptive statistics'],
            tools: ['Python (Pandas)', 'Jupyter Notebooks', 'Google Sheets'],
            practiceTasks: [
              'Clean a messy CSV with 5 types of data quality issues',
              'Calculate mean, median, mode, and standard deviation for a dataset',
              'Find and remove duplicate records from a 10,000-row dataset',
            ],
            finalDeliverable: 'Clean Dataset + Analysis Report: a Jupyter notebook showing the full cleaning process, descriptive statistics, and 3 key observations.',
            estimatedTime: '1.5 weeks',
          },
          {
            id: 'ds-f-2',
            title: 'Visualisation & Insight',
            goal: 'Transform raw data into clear, insightful visualisations and a stakeholder-ready dashboard.',
            skills: ['Chart type selection', 'Matplotlib/Seaborn', 'Insight writing', 'Dashboard layout principles'],
            tools: ['Matplotlib', 'Seaborn', 'Looker Studio'],
            practiceTasks: [
              'Choose the right chart type for 5 different data scenarios',
              'Build a 6-chart analysis in Python showing e-commerce trends',
              'Translate 3 chart insights into 1-sentence stakeholder findings',
            ],
            finalDeliverable: 'Data Dashboard: Looker Studio report with 6+ visualisations, filters, and a written insight summary for a non-technical audience.',
            estimatedTime: '1.5 weeks',
          },
          {
            id: 'ds-f-3',
            title: 'ML Concepts (Intro)',
            goal: 'Understand the core concepts of machine learning and run your first classification model.',
            skills: ['Supervised vs unsupervised', 'Train/test split', 'Accuracy metrics', 'Scikit-learn basics'],
            tools: ['scikit-learn', 'Jupyter Notebooks'],
            practiceTasks: [
              'Explain overfitting and underfitting using a visual example',
              'Train a logistic regression model on the Titanic dataset',
              'Evaluate a model using accuracy, precision, recall, and F1',
            ],
            finalDeliverable: 'ML Intro Notebook: trained classification model with accuracy metrics, confusion matrix, and a plain-English explanation of the results.',
            estimatedTime: '1 week',
          },
        ],
      },
      {
        level: 'Intermediate',
        description: 'Apply data skills to real business scenarios. Build eligibility scoring systems and integrate AI workflow tools.',
        workPackages: [
          {
            id: 'ds-i-1',
            title: 'Business Analytics Case',
            goal: 'Solve a real-world business problem using data, from question framing to actionable recommendation.',
            skills: ['Business question framing', 'Cohort analysis', 'A/B test interpretation', 'Recommendation writing'],
            tools: ['Python', 'Looker Studio', 'Notion'],
            practiceTasks: [
              'Frame 3 analytical questions from a business problem statement',
              'Run a cohort retention analysis on a SaaS dataset',
              'Write a 1-page recommendation from an A/B test result',
            ],
            finalDeliverable: 'Business Analytics Case Study: analytical question, dataset exploration, cohort analysis, and a stakeholder recommendation deck.',
            estimatedTime: '2 weeks',
          },
          {
            id: 'ds-i-2',
            title: 'AI Workflow Tools',
            goal: 'Integrate AI APIs into a data workflow to automate classification, summarisation, and extraction tasks.',
            skills: ['Prompt engineering', 'OpenAI API', 'Chain-of-thought reasoning', 'Output parsing'],
            tools: ['OpenAI API', 'LangChain', 'Python'],
            practiceTasks: [
              'Use GPT to auto-classify 100 customer support tickets by category',
              'Extract structured data (name, date, amount) from 20 raw text records',
              'Build a summarisation pipeline for weekly sales reports',
            ],
            finalDeliverable: 'AI Workflow Tool: Python script or Jupyter notebook that automates a data task using LLM, with accuracy validation and time savings calculation.',
            estimatedTime: '2 weeks',
          },
          {
            id: 'ds-i-3',
            title: 'Scoring Systems (Eligibility Logic)',
            goal: 'Design and implement a rule-based or ML-powered scoring model for business eligibility decisions.',
            skills: ['Scoring model design', 'Weighted attribute models', 'Threshold logic', 'Model explainability'],
            tools: ['Python', 'Google Sheets', 'scikit-learn'],
            practiceTasks: [
              'Design a weighted eligibility score for internship candidates (5 attributes)',
              'Build a rule-based loan eligibility model with 4 criteria',
              'Visualise score distribution across a test cohort',
            ],
            finalDeliverable: 'Eligibility Scoring Model: documented model design, Python implementation, score distribution chart, and a plain-English decision report.',
            estimatedTime: '2 weeks',
          },
        ],
      },
      {
        level: 'Advanced',
        description: 'Operate as an AI product thinker. Design AI-powered features, build monitoring logic, and write PRDs.',
        workPackages: [
          {
            id: 'ds-a-1',
            title: 'Applied AI Product Thinking',
            goal: 'Define, scope, and write a Product Requirements Document (PRD) for an AI-powered product feature.',
            skills: ['AI feature scoping', 'PRD writing', 'Evaluation metrics for AI', 'User story mapping'],
            tools: ['Notion', 'Figma (wireframe)', 'OpenAI API'],
            practiceTasks: [
              'Write user stories for an AI content moderation feature',
              'Define evaluation metrics for an AI recommendation engine',
              'Wireframe the UI for an AI-assisted onboarding flow',
            ],
            finalDeliverable: 'AI Feature PRD: full product requirements document with user stories, success metrics, edge cases, and a UI wireframe.',
            estimatedTime: '2 weeks',
          },
          {
            id: 'ds-a-2',
            title: 'Monitoring Concepts',
            goal: 'Understand data drift, model degradation, and how to build lightweight monitoring for ML systems in production.',
            skills: ['Data drift detection', 'Model performance monitoring', 'Alerting logic', 'Retraining triggers'],
            tools: ['Python', 'Evidently AI (open-source)', 'Looker Studio'],
            practiceTasks: [
              'Generate a data drift report on two time-separated datasets',
              'Define alert thresholds for 3 key model performance metrics',
              'Write a retraining SOP for a classification model',
            ],
            finalDeliverable: 'Monitoring Dashboard + SOP: drift report, performance monitoring setup, alert thresholds, and a retraining standard operating procedure.',
            estimatedTime: '2 weeks',
          },
        ],
      },
    ],
    rubric: {
      passMark: 70,
      distincionMark: 85,
      categories: [
        { name: 'Analytical Rigour', weight: 30, criteria: ['Correct statistical methods applied', 'Data cleaning documented', 'Assumptions stated'] },
        { name: 'Insight Quality', weight: 25, criteria: ['Insights are specific and actionable', 'Supported by data', 'Clearly communicated'] },
        { name: 'Visualisation', weight: 20, criteria: ['Appropriate chart types', 'Readable and labelled', 'Tells a clear story'] },
        { name: 'Code Quality', weight: 15, criteria: ['Readable Python code', 'Commented sections', 'Reproducible notebook'] },
        { name: 'Documentation', weight: 10, criteria: ['Notebook is structured', 'Report is concise', 'Non-technical audience considered'] },
      ],
    },
    portfolioOutputs: [
      { id: 'ds-po-1', title: 'Dashboard', description: 'Live Looker Studio dashboard with interactive filters and stakeholder-ready insights.', level: 'Foundation', format: 'Looker Studio live link' },
      { id: 'ds-po-2', title: 'Insight Report', description: 'Business analytics case study with analysis notebook and recommendation deck.', level: 'Intermediate', format: 'Notion page + Jupyter notebook' },
      { id: 'ds-po-3', title: 'Scoring Model', description: 'Documented eligibility scoring model with score distributions and decision logic.', level: 'Intermediate', format: 'Jupyter notebook + PDF report' },
      { id: 'ds-po-4', title: 'AI Feature PRD', description: 'Full product requirements document for an AI-powered feature with wireframes.', level: 'Advanced', format: 'Notion PRD + Figma wireframe' },
    ],
  },

  // ─────────────────────────────────────────────────────────────
  // 5. CYBER SECURITY
  // ─────────────────────────────────────────────────────────────
  {
    id: 'ws-cs',
    name: 'Cyber Security',
    shortName: 'Security',
    description: 'Learn threat modelling, security testing, and incident response using real-world tools and frameworks used by security teams.',
    tagline: 'Think like an attacker. Defend like a professional.',
    icon: 'ShieldCheck',
    color: 'text-green-400',
    accentColor: 'green',
    order: 5,
    cohortIds: ['cohort-1', 'cohort-2', 'cohort-3'],
    projectIds: [],
    totalEstimatedWeeks: 10,
    internshipWeight: 100,
    tools: [
      { name: 'Kali Linux', category: 'Testing Environment', description: 'Penetration testing OS with pre-installed security tools', required: true },
      { name: 'Wireshark', category: 'Network Analysis', description: 'Packet capture and protocol analysis', required: true },
      { name: 'Burp Suite Community', category: 'Web Testing', description: 'HTTP interceptor for web application security testing', required: true },
      { name: 'Nmap', category: 'Reconnaissance', description: 'Network scanning, port discovery, OS fingerprinting', required: true },
      { name: 'Metasploit (lab only)', category: 'Exploitation', description: 'Controlled exploitation framework for lab environments', required: false },
      { name: 'OWASP ZAP', category: 'Web Testing', description: 'Automated web vulnerability scanner', required: false },
      { name: 'TryHackMe / Hack The Box', category: 'Practice Platform', description: 'Guided CTF challenges and learning rooms', required: true },
      { name: 'Notion / Google Docs', category: 'Documentation', description: 'Vulnerability reports, playbooks, audit docs', required: true },
    ],
    syllabus: [
      {
        level: 'Foundation',
        description: 'Understand the security landscape, networking fundamentals, and Linux command line operations used by security professionals.',
        workPackages: [
          {
            id: 'cs-f-1',
            title: 'Security Basics',
            goal: 'Understand the CIA triad, threat landscape, and key security frameworks used in industry.',
            skills: ['CIA triad (Confidentiality, Integrity, Availability)', 'Common threat categories', 'MITRE ATT&CK basics', 'Security posture assessment'],
            tools: ['TryHackMe (Pre-Security path)', 'Notion'],
            practiceTasks: [
              'Map a real-world breach to the CIA triad to identify what was compromised',
              'Research and summarise 3 CVEs from the past 12 months',
              'Complete the TryHackMe "Intro to Cybersecurity" room',
            ],
            finalDeliverable: 'Security Threat Overview Report: 3-page document mapping the current threat landscape, key frameworks, and 2 real-world breach case studies.',
            estimatedTime: '1 week',
          },
          {
            id: 'cs-f-2',
            title: 'Networking Fundamentals',
            goal: 'Understand TCP/IP, DNS, HTTP, and how to read and interpret packet captures.',
            skills: ['OSI model', 'TCP/IP stack', 'DNS and HTTP protocols', 'Packet capture analysis'],
            tools: ['Wireshark', 'TryHackMe (Networking rooms)'],
            practiceTasks: [
              'Capture and identify HTTP vs. HTTPS traffic in Wireshark',
              'Trace a DNS query from browser to resolution in a packet capture',
              'Complete TryHackMe "Networking Fundamentals" room',
            ],
            finalDeliverable: 'Networking Lab Report: annotated Wireshark captures of DNS, HTTP, and TCP handshake with protocol analysis notes.',
            estimatedTime: '1.5 weeks',
          },
          {
            id: 'cs-f-3',
            title: 'Linux Basics',
            goal: 'Navigate and operate a Linux system via command line at the level required for security tooling.',
            skills: ['Filesystem navigation', 'User and permission management', 'Bash scripting basics', 'Log file analysis'],
            tools: ['Kali Linux', 'TryHackMe (Linux rooms)'],
            practiceTasks: [
              'Set up a Kali Linux VM and complete the basic system orientation',
              'Write a bash script that finds all files modified in the last 24 hours',
              'Identify a suspicious login from a sample auth.log file',
            ],
            finalDeliverable: 'Linux Lab Workbook: completed exercises covering file navigation, user management, bash scripting, and log analysis with annotated outputs.',
            estimatedTime: '1 week',
          },
        ],
      },
      {
        level: 'Intermediate',
        description: 'Apply security testing techniques to web applications. Learn OWASP vulnerabilities and build incident response skills.',
        workPackages: [
          {
            id: 'cs-i-1',
            title: 'OWASP Overview',
            goal: 'Understand and demonstrate the OWASP Top 10 vulnerabilities in a controlled lab environment.',
            skills: ['SQL Injection', 'XSS (Stored and Reflected)', 'IDOR', 'Security misconfigurations', 'Insecure authentication'],
            tools: ['DVWA (Damn Vulnerable Web Application)', 'Burp Suite', 'OWASP ZAP'],
            practiceTasks: [
              'Exploit a SQL injection vulnerability in DVWA (low security level)',
              'Demonstrate a reflected XSS payload in a controlled form',
              'Identify 3 misconfigurations in a sample application config file',
            ],
            finalDeliverable: 'OWASP Lab Report: documented reproduction of 5 OWASP Top 10 vulnerabilities in DVWA, with screenshots, payloads used, and remediation steps.',
            estimatedTime: '2 weeks',
          },
          {
            id: 'cs-i-2',
            title: 'Security Testing Workflow',
            goal: 'Conduct a structured security test of a web application following a professional methodology.',
            skills: ['Reconnaissance methodology', 'Vulnerability enumeration', 'Manual vs automated testing', 'Evidence documentation'],
            tools: ['Nmap', 'Burp Suite', 'OWASP ZAP', 'Notion'],
            practiceTasks: [
              'Run an Nmap scan against a target VM and interpret the results',
              'Perform a manual test of all input fields on a target application',
              'Document a vulnerability finding using a standard report template',
            ],
            finalDeliverable: 'Vulnerability Assessment Report: structured security test of a lab application with risk-rated findings, evidence screenshots, and remediation recommendations.',
            estimatedTime: '2 weeks',
          },
          {
            id: 'cs-i-3',
            title: 'Incident Response Basics',
            goal: 'Learn the incident response lifecycle and produce a professional IR playbook for a common attack scenario.',
            skills: ['IR lifecycle (Preparation, Identification, Containment, Eradication, Recovery)', 'Log analysis for IR', 'Containment strategies', 'Post-incident reporting'],
            tools: ['Splunk Free / ELK (logs)', 'Notion', 'TryHackMe (IR rooms)'],
            practiceTasks: [
              'Identify the entry point of a ransomware attack from a log sample',
              'Write a containment decision tree for a phishing incident',
              'Complete TryHackMe "Incident Response and Forensics" room',
            ],
            finalDeliverable: 'Incident Response Playbook: phishing and ransomware IR playbooks with detection criteria, containment steps, communication templates, and lessons learned.',
            estimatedTime: '1.5 weeks',
          },
        ],
      },
      {
        level: 'Advanced',
        description: 'Think and operate like a senior security professional. Conduct threat modelling sessions and deliver a full security audit.',
        workPackages: [
          {
            id: 'cs-a-1',
            title: 'Threat Modeling',
            goal: 'Conduct a STRIDE-based threat modelling session for a real application architecture.',
            skills: ['STRIDE methodology', 'Data Flow Diagrams (DFDs)', 'Trust boundary identification', 'Risk prioritisation (DREAD)'],
            tools: ['Microsoft Threat Modeling Tool / OWASP Threat Dragon', 'Notion', 'Excalidraw'],
            practiceTasks: [
              'Draw a DFD for a 3-tier web application with authentication',
              'Apply STRIDE to each element and identify 10 threats',
              'Prioritise findings using DREAD scoring',
            ],
            finalDeliverable: 'Threat Model Document: DFD, STRIDE analysis, DREAD-prioritised threat register, and mitigation recommendations for a target architecture.',
            estimatedTime: '2 weeks',
          },
          {
            id: 'cs-a-2',
            title: 'Security Audit Project',
            goal: 'Perform a comprehensive security audit of an application or infrastructure, producing a boardroom-ready audit report.',
            skills: ['Audit scope definition', 'Risk-based testing', 'Executive summary writing', 'Remediation roadmap'],
            tools: ['Burp Suite', 'Nmap', 'OWASP ZAP', 'Notion'],
            practiceTasks: [
              'Define the audit scope and rules of engagement for a target system',
              'Run a full security assessment and compile findings into a risk register',
              'Write a 1-page executive summary suitable for a non-technical audience',
            ],
            finalDeliverable: 'Security Audit Report: executive summary, risk register, detailed findings with CVSS scores, remediation roadmap, and a 30/60/90-day fix plan.',
            estimatedTime: '3 weeks',
          },
        ],
      },
    ],
    rubric: {
      passMark: 70,
      distincionMark: 85,
      categories: [
        { name: 'Technical Accuracy', weight: 35, criteria: ['Correct tool usage', 'Accurate vulnerability identification', 'Reproducible findings'] },
        { name: 'Methodology', weight: 25, criteria: ['Structured approach followed', 'Scope defined before testing', 'Evidence documented throughout'] },
        { name: 'Report Quality', weight: 25, criteria: ['Clear risk ratings', 'Actionable remediation steps', 'Executive summary present'] },
        { name: 'Ethical Conduct', weight: 15, criteria: ['Testing confined to lab scope', 'No real systems targeted', 'Responsible disclosure principles applied'] },
      ],
    },
    portfolioOutputs: [
      { id: 'cs-po-1', title: 'Threat Model', description: 'STRIDE-based threat model with DFD, threat register, and DREAD-prioritised mitigations.', level: 'Advanced', format: 'PDF report + Threat Dragon file' },
      { id: 'cs-po-2', title: 'Vulnerability Report', description: 'Professional vulnerability assessment report with risk-rated findings and evidence.', level: 'Intermediate', format: 'PDF report' },
      { id: 'cs-po-3', title: 'Incident Response Playbook', description: 'IR playbooks for phishing and ransomware with containment, communication, and recovery steps.', level: 'Intermediate', format: 'Notion page + PDF' },
      { id: 'cs-po-4', title: 'Audit Report', description: 'Full security audit report with executive summary, CVSS findings, and a remediation roadmap.', level: 'Advanced', format: 'PDF report' },
    ],
  },

  // ─────────────────────────────────────────────────────────────
  // 6. 3D VISUALIZATION
  // ─────────────────────────────────────────────────────────────
  {
    id: 'ws-3d',
    name: '3D Visualization',
    shortName: '3D Viz',
    description: 'Create photorealistic product renders, architectural visualisations, and CGI-grade animations using Blender and Cinema 4D.',
    tagline: 'Make it look real. Make it look better than real.',
    icon: 'Boxes',
    color: 'text-cyan-400',
    accentColor: 'cyan',
    order: 6,
    cohortIds: ['cohort-1', 'cohort-2', 'cohort-3'],
    projectIds: [],
    totalEstimatedWeeks: 12,
    internshipWeight: 100,
    tools: [
      { name: 'Blender', category: '3D Modelling', description: 'Free, industry-standard 3D creation suite', required: true },
      { name: 'Cinema 4D', category: '3D Modelling', description: 'Professional 3D for motion graphics and product viz', required: false },
      { name: 'Substance Painter', category: 'Texturing', description: 'PBR texture painting and material creation', required: false },
      { name: 'Octane / Cycles', category: 'Rendering', description: 'GPU-accelerated photorealistic rendering', required: true },
      { name: 'Adobe After Effects', category: 'Post-Production', description: 'Compositing, colour, and VFX overlays', required: false },
      { name: 'Lightroom / Photoshop', category: 'Post-Production', description: 'Final colour grade and image retouching', required: true },
      { name: 'HDRi Haven / Poly Haven', category: 'Assets', description: 'Free HDRI maps and 3D assets', required: true },
      { name: 'KeyShot', category: 'Product Rendering', description: 'Rapid product visualisation rendering', required: false },
    ],
    syllabus: [
      {
        level: 'Foundation',
        description: 'Learn 3D fundamentals: modelling, shading, lighting, and rendering your first photorealistic scene.',
        workPackages: [
          {
            id: '3d-f-1',
            title: '3D Basics',
            goal: 'Navigate Blender confidently, model basic objects, and understand the 3D coordinate system.',
            skills: ['Viewport navigation', 'Mesh modelling (extrude, loop cut, bevel)', 'Boolean operations', 'Object vs Edit mode'],
            tools: ['Blender'],
            practiceTasks: [
              'Model a simple product (a coffee mug or headphones) from a reference image',
              'Apply Boolean operations to create a cutaway cross-section of an object',
              'Build a simple room scene using only primitive shapes',
            ],
            finalDeliverable: 'Product Model: clean, subdivision-ready 3D model of a product with proper topology, rendered from 3 angles.',
            estimatedTime: '2 weeks',
          },
          {
            id: '3d-f-2',
            title: 'Materials & Lighting',
            goal: 'Create photorealistic PBR materials and set up a 3-point lighting rig using HDRI and area lights.',
            skills: ['PBR material workflow (roughness, metallic, normal)', 'Shader node basics', 'HDRI lighting', '3-point studio light setup'],
            tools: ['Blender Cycles', 'HDRi Haven', 'Substance Painter (optional)'],
            practiceTasks: [
              'Create a brushed metal, matte plastic, and glass material using Shader nodes',
              'Set up an HDRI-lit studio scene and compare 3 different HDRIs',
              'Replicate a product photography lighting setup using area lights',
            ],
            finalDeliverable: 'Material & Lighting Study: 3 objects with distinct PBR materials (metal, plastic, glass) in a studio lighting setup, rendered at 2K.',
            estimatedTime: '1.5 weeks',
          },
          {
            id: '3d-f-3',
            title: 'Rendering & Composition',
            goal: 'Configure render settings for quality output and apply compositional rules to create hero shots.',
            skills: ['Cycles vs EEVEE', 'Render settings (samples, denoising)', 'Camera framing and DoF', 'Post-render colour grading'],
            tools: ['Blender Cycles', 'Lightroom / Photoshop'],
            practiceTasks: [
              'Compare a Cycles render vs EEVEE render of the same scene',
              'Apply a shallow depth of field to a product shot for hero framing',
              'Colour grade a render in Lightroom to match a reference brand palette',
            ],
            finalDeliverable: 'Hero Product Render: 2K+ final render of a product shot with intentional DoF, composition, and a Lightroom-graded final image.',
            estimatedTime: '1 week',
          },
        ],
      },
      {
        level: 'Intermediate',
        description: 'Create commercial-grade product and architectural visualisations for real client deliverables.',
        workPackages: [
          {
            id: '3d-i-1',
            title: 'Product Visualisation',
            goal: 'Create a client-ready product CGI pack with multiple angles, colour variants, and lifestyle context shots.',
            skills: ['Scene setup for product viz', 'Material variants (colour swaps)', 'Turntable animation', 'Export for digital and print'],
            tools: ['Blender', 'KeyShot (optional)', 'Photoshop'],
            practiceTasks: [
              'Create 3 colour variants of a product by swapping material parameters',
              'Set up a 360° turntable animation (60 frames)',
              'Composite a product render onto a lifestyle photograph background',
            ],
            finalDeliverable: 'Product CGI Pack: 5 hero renders from different angles, 3 colour variants, and a 10-second turntable animation — all at 2K+.',
            estimatedTime: '2 weeks',
          },
          {
            id: '3d-i-2',
            title: 'Architectural Visualisation',
            goal: 'Build and render a complete interior or exterior architectural scene using real design reference.',
            skills: ['Architectural modelling techniques', 'Interior vs exterior lighting', 'Camera animation (dolly/push in)', 'CAD import / blueprint tracing'],
            tools: ['Blender', 'Cycles', 'Photoshop'],
            practiceTasks: [
              'Model a simple interior room from a floor plan blueprint',
              'Render the same room in 3 different times-of-day lighting conditions',
              'Create a camera animation that pushes into the space (5 seconds)',
            ],
            finalDeliverable: 'Architectural Visualisation Set: 4 final stills (morning, afternoon, evening, detail shot) + a 5-second camera move, at 2K+.',
            estimatedTime: '2 weeks',
          },
          {
            id: '3d-i-3',
            title: 'Walkthrough Basics',
            goal: 'Create a smooth architectural walkthrough animation that guides the viewer through a space.',
            skills: ['Camera path animation', 'Motion blur', 'Frame rate and codec selection', 'Smooth interpolation techniques'],
            tools: ['Blender', 'Adobe Premiere Pro'],
            practiceTasks: [
              'Animate a 10-second camera walkthrough through a room using a Bezier path',
              'Apply motion blur and compare render times vs quality',
              'Edit and grade the rendered sequence in Premiere Pro',
            ],
            finalDeliverable: 'Walkthrough Video (20–30 seconds): smooth, graded architectural walkthrough of an interior or exterior space, exported at 1080p minimum.',
            estimatedTime: '2 weeks',
          },
        ],
      },
      {
        level: 'Advanced',
        description: 'Operate at commercial CGI studio level. Master complex lighting, lookdev, and deliver a complete production workflow.',
        workPackages: [
          {
            id: '3d-a-1',
            title: 'Commercial CGI Workflow',
            goal: 'Plan and execute a commercial 3D production from concept brief to final deliverable, matching a brand reference.',
            skills: ['CGI art direction', 'Scene asset management', 'Render farm / batch rendering', 'Client delivery formats'],
            tools: ['Blender', 'Cycles', 'Frame.io / Notion'],
            practiceTasks: [
              'Interpret a commercial CGI brief and produce a mood board with references',
              'Manage a scene with 10+ assets, lights, and camera setups using collections',
              'Batch render 10 frames and assemble a final delivery folder',
            ],
            finalDeliverable: 'Commercial CGI Production: brand-aligned product or concept scene with production documentation, multi-angle final renders, and delivery folder.',
            estimatedTime: '3 weeks',
          },
          {
            id: '3d-a-2',
            title: 'Advanced Lighting & Lookdev',
            goal: 'Achieve photorealistic lighting and lookdev that matches a reference photograph or client style guide.',
            skills: ['Light matching from reference', 'IES profiles', 'LUT-based lookdev', 'Render layer compositing'],
            tools: ['Blender', 'Octane (if available)', 'Photoshop / Nuke basics'],
            practiceTasks: [
              'Recreate the lighting setup of a reference product photograph in 3D',
              'Apply an IES light profile to a practical lamp source',
              'Build a render layer composite in Blender for non-destructive post-production',
            ],
            finalDeliverable: 'Hero Render Breakdown: final hero render + side-by-side lighting reference match, render layer breakdown, and LUT/lookdev documentation.',
            estimatedTime: '2 weeks',
          },
        ],
      },
    ],
    rubric: {
      passMark: 70,
      distincionMark: 85,
      categories: [
        { name: 'Technical Quality', weight: 35, criteria: ['Clean topology', 'Photorealistic materials', 'Render artefact-free'] },
        { name: 'Lighting & Composition', weight: 25, criteria: ['Believable light sources', 'Strong compositional framing', 'Mood aligned with brief'] },
        { name: 'Creative Direction', weight: 20, criteria: ['Brand/brief alignment', 'Unique visual treatment', 'Intentional art direction'] },
        { name: 'Production Workflow', weight: 15, criteria: ['Scene organised with collections', 'Naming conventions', 'Delivery in correct formats'] },
        { name: 'Post-Production', weight: 5, criteria: ['Colour grading applied', 'Clean final export', 'No compression artefacts'] },
      ],
    },
    portfolioOutputs: [
      { id: '3d-po-1', title: 'Product CGI Pack', description: '5 hero renders, 3 colour variants, and a turntable animation of a single product.', level: 'Intermediate', format: 'JPEG/PNG 2K+ + MP4 video' },
      { id: '3d-po-2', title: 'Archviz Set', description: '4 architectural stills across different lighting conditions and a detail shot.', level: 'Intermediate', format: 'JPEG 2K+ per image' },
      { id: '3d-po-3', title: 'Walkthrough Video', description: '20–30 second graded architectural walkthrough animation.', level: 'Intermediate', format: 'MP4 1080p minimum' },
      { id: '3d-po-4', title: 'Hero Render Breakdown', description: 'Final commercial hero render with lighting reference match and render layer documentation.', level: 'Advanced', format: 'PDF breakdown + PNG final render' },
    ],
  },
]
